/* ===== 데일리 별자리 =====
   ZODIAC = 정적 메타(고정: 글리프·날짜·별자리 점). 매일 안 바뀜.
   DAILY_SEED = 생성물(Phase 2서 daily/horoscope.json 으로 대체) — 날짜 + 별자리별 ko/en 운세.
   프론트(engine.js)가 ZODIAC[i] + getDaily().readings[key] 를 합쳐 엔딩 카드로 렌더.
   stars = 정규화(0..1) 별점 — 이제 '장식용 별자리'(자동 점등, 상호작용 없음). */
/* stars = 정규화(0..1, y는 아래로) 별 위치, 실제 별자리 선 그림에 근사.
   paths = 잇는 선(각 path = 별 인덱스 순서). 가지가 여러 개인 별자리(쌍둥이/전갈 집게/물병 물병 등)는 path 여러 개. */
const ZODIAC = [
  { key:"aries",       glyph:"♈",
    stars:[{x:0.13,y:0.273},{x:0.691,y:0.489},{x:0.855,y:0.64},{x:0.87,y:0.727}], paths:[[0,1,2,3]],
    ko:{ name:"양자리",     dates:"3.21–4.19" }, en:{ name:"Aries",       dates:"Mar 21 – Apr 19" } },
  { key:"taurus",      glyph:"♉",
    stars:[{x:0.238,y:0.238},{x:0.787,y:0.618},{x:0.841,y:0.685},{x:0.87,y:0.762},{x:0.717,y:0.726},{x:0.13,y:0.539}], paths:[[0,1,2,3,4,5]],
    ko:{ name:"황소자리",   dates:"4.20–5.20" }, en:{ name:"Taurus",      dates:"Apr 20 – May 20" } },
  { key:"gemini",      glyph:"♊",
    stars:[{x:0.226,y:0.194},{x:0.13,y:0.347},{x:0.681,y:0.461},{x:0.356,y:0.586},{x:0.87,y:0.564},{x:0.737,y:0.806}], paths:[[0,2,4],[1,3,5],[2,3]],
    ko:{ name:"쌍둥이자리", dates:"5.21–6.21" }, en:{ name:"Gemini",      dates:"May 21 – Jun 21" } },
  { key:"cancer",      glyph:"♋",
    stars:[{x:0.417,y:0.13},{x:0.448,y:0.406},{x:0.436,y:0.531},{x:0.689,y:0.87},{x:0.311,y:0.769}], paths:[[0,1,2],[2,3],[2,4]],
    ko:{ name:"게자리",     dates:"6.22–7.22" }, en:{ name:"Cancer",      dates:"Jun 22 – Jul 22" } },
  { key:"leo",         glyph:"♌",
    stars:[{x:0.735,y:0.678},{x:0.74,y:0.556},{x:0.665,y:0.479},{x:0.685,y:0.387},{x:0.828,y:0.322},{x:0.87,y:0.378},{x:0.339,y:0.461},{x:0.339,y:0.591},{x:0.13,y:0.612}], paths:[[5,4,3,2,1,0],[0,7,8,6,2]],
    ko:{ name:"사자자리",   dates:"7.23–8.22" }, en:{ name:"Leo",         dates:"Jul 23 – Aug 22" } },
  { key:"virgo",       glyph:"♍",
    stars:[{x:0.197,y:0.815},{x:0.507,y:0.538},{x:0.408,y:0.401},{x:0.362,y:0.186},{x:0.13,y:0.514},{x:0.662,y:0.517},{x:0.87,y:0.446},{x:0.302,y:0.655}], paths:[[3,2,1,7,0],[1,4],[1,5,6]],
    ko:{ name:"처녀자리",   dates:"8.23–9.22" }, en:{ name:"Virgo",       dates:"Aug 23 – Sep 22" } },
  { key:"libra",       glyph:"♎",
    stars:[{x:0.749,y:0.44},{x:0.457,y:0.13},{x:0.251,y:0.381},{x:0.601,y:0.87}], paths:[[1,0,3],[1,2,0]],
    ko:{ name:"천칭자리",   dates:"9.23–10.22" }, en:{ name:"Libra",       dates:"Sep 23 – Oct 22" } },
  { key:"scorpio",     glyph:"♏",
    stars:[{x:0.815,y:0.13},{x:0.849,y:0.219},{x:0.859,y:0.329},{x:0.711,y:0.312},{x:0.657,y:0.339},{x:0.614,y:0.396},{x:0.52,y:0.588},{x:0.508,y:0.706},{x:0.491,y:0.842},{x:0.375,y:0.87},{x:0.208,y:0.862},{x:0.141,y:0.772},{x:0.174,y:0.737},{x:0.234,y:0.676}], paths:[[0,1],[2,1],[1,3,4,5,6,7,8,9,10,11,12,13]],
    ko:{ name:"전갈자리",   dates:"10.23–11.22" }, en:{ name:"Scorpius",    dates:"Oct 23 – Nov 22" } },
  { key:"sagittarius", glyph:"♐",
    stars:[{x:0.87,y:0.528},{x:0.686,y:0.496},{x:0.647,y:0.747},{x:0.601,y:0.253},{x:0.387,y:0.339},{x:0.271,y:0.301},{x:0.13,y:0.376},{x:0.183,y:0.499}], paths:[[0,1,3,4,5,6,7,2,1]],
    ko:{ name:"궁수자리",   dates:"11.23–12.21" }, en:{ name:"Sagittarius", dates:"Nov 23 – Dec 21" } },
  { key:"capricorn",   glyph:"♑",
    stars:[{x:0.87,y:0.277},{x:0.845,y:0.357},{x:0.636,y:0.723},{x:0.299,y:0.623},{x:0.13,y:0.404},{x:0.187,y:0.422},{x:0.471,y:0.443}], paths:[[1,2,3,4,5,6,0,1]],
    ko:{ name:"염소자리",   dates:"12.22–1.19" }, en:{ name:"Capricornus", dates:"Dec 22 – Jan 19" } },
  { key:"aquarius",    glyph:"♒",
    stars:[{x:0.48,y:0.361},{x:0.651,y:0.466},{x:0.401,y:0.383},{x:0.365,y:0.355},{x:0.333,y:0.357},{x:0.382,y:0.327},{x:0.425,y:0.511},{x:0.246,y:0.507},{x:0.138,y:0.476},{x:0.13,y:0.537},{x:0.236,y:0.673},{x:0.87,y:0.545},{x:0.845,y:0.536}], paths:[[11,12,1,0],[0,2,3,4],[3,5],[0,6,7,10],[7,8,9]],
    ko:{ name:"물병자리",   dates:"1.20–2.18" }, en:{ name:"Aquarius",    dates:"Jan 20 – Feb 18" } },
  { key:"pisces",      glyph:"♓",
    stars:[{x:0.13,y:0.741},{x:0.222,y:0.69},{x:0.272,y:0.679},{x:0.396,y:0.647},{x:0.46,y:0.652},{x:0.681,y:0.666},{x:0.804,y:0.688},{x:0.822,y:0.675},{x:0.87,y:0.731},{x:0.759,y:0.759},{x:0.205,y:0.624},{x:0.267,y:0.511},{x:0.322,y:0.293},{x:0.357,y:0.241},{x:0.347,y:0.342}], paths:[[0,1,2,3,4,5],[5,6],[6,7,8,9,6],[0,10,11,12],[12,13,14,12]],
    ko:{ name:"물고기자리", dates:"2.19–3.20" }, en:{ name:"Pisces",      dates:"Feb 19 – Mar 20" } },
];

/* 하루치 운세 — Phase 2의 생성 JSON과 같은 모양. 톤 = 아련·포근, 점괘 아닌 한 호흡의 위로(별 읽는 목소리).
   body = 문장 배열(한 줄=한 문장) → 엔딩 카드에서 한 줄씩 페이드로 흘러나옴. ~10문장. */
const DAILY_SEED = {
  date: "2026-06-24",
  readings: {
    aries: {
      ko:{ teaser:"서두르던 걸음이 잠깐 숨을 고른다.", body:[
        "오늘 당신의 별은 빠르기보다 깊이를 비춥니다.",
        "앞서 나가려던 걸음이 잠시 숨을 고르는 날이에요.",
        "서두르지 않아도 길은 사라지지 않습니다.",
        "오히려 멈춘 자리에서 보이지 않던 갈래가 드러나요.",
        "곁에 있는 사람의 표정을 한 번 더 살펴보세요.",
        "작은 기다림이 오늘은 가장 빠른 지름길이 됩니다.",
        "이기려는 마음을 잠깐 내려놓아도 잃을 건 없어요.",
        "당신의 열정은 식는 게 아니라 데워지는 중이에요.",
        "천천히 쥔 것이 더 오래 당신 손에 남습니다.",
        "오늘 밤, 서두르지 않은 자신을 조용히 칭찬해 주세요." ] },
      en:{ teaser:"A hurried step pauses to breathe.", body:[
        "Tonight's reading favors depth rather than speed.",
        "The step that wanted to race ahead pauses to breathe.",
        "The road does not vanish just because you slow down.",
        "In fact, a path you couldn't see appears where you stop.",
        "Look once more at the face of the person beside you.",
        "Today a small wait becomes the fastest shortcut.",
        "Set down the urge to win for a moment — you lose nothing.",
        "Your fire isn't cooling; it's warming through.",
        "What you take hold of slowly stays with you longer.",
        "Tonight, quietly praise yourself for not rushing." ] } },
    taurus: {
      ko:{ teaser:"익숙한 자리에서 작은 빛을 발견한다.", body:[
        "오늘 당신의 별은 멀리가 아니라 발밑을 비춥니다.",
        "무언가를 바꾸려 애쓰지 않아도 좋은 하루예요.",
        "늘 지나치던 자리에 오늘은 새 결이 보입니다.",
        "익숙함은 지루함이 아니라 단단함이에요.",
        "같은 길도 오늘은 조금 다른 빛으로 당신을 맞아요.",
        "가진 것을 세어보면 생각보다 따뜻할 거예요.",
        "서두른 변화보다 천천히 깊어지는 게 당신답습니다.",
        "작은 안정 하나가 오늘 마음을 든든히 받쳐줘요.",
        "누가 재촉해도 당신의 속도를 믿어도 됩니다.",
        "오늘 밤은 익숙한 것에 고맙다고 말해보세요." ] },
      en:{ teaser:"A small light in a familiar place.", body:[
        "Tonight's reading turns your attention to the ground beneath you, not the distance.",
        "It's a good day not to force any change at all.",
        "A place you always walked past shows you a new texture today.",
        "The familiar isn't dullness; it's steadiness.",
        "Even the same road greets you in a slightly different light.",
        "Count what you already hold — it's warmer than you thought.",
        "Deepening slowly suits you more than a hurried change.",
        "One small steadiness holds your heart up today.",
        "Even if others rush you, you may trust your own pace.",
        "Tonight, try saying thank you to the familiar things." ] } },
    gemini: {
      ko:{ teaser:"두 마음이 오늘은 같은 곳을 본다.", body:[
        "오늘 당신의 별은 흩어진 생각을 한 줄로 모읍니다.",
        "두 갈래로 갈리던 마음이 같은 곳을 바라보는 날이에요.",
        "어느 쪽이 맞나 따지느라 지쳤다면 이제 쉬어도 돼요.",
        "머릿속 소음이 잦아들고 또렷한 한 마디가 남습니다.",
        "망설이며 삼켰던 말을 오늘은 가볍게 건네보세요.",
        "당신의 말은 생각보다 부드럽게 가닿을 거예요.",
        "솔직함이 관계를 무너뜨리지 않습니다, 오히려 잇습니다.",
        "가벼운 농담 하나가 무거운 공기를 풀어줘요.",
        "오늘은 듣는 일도 말하는 일만큼 당신을 빛냅니다.",
        "잠들기 전, 하고 싶던 말 한 줄을 적어두어도 좋아요." ] },
      en:{ teaser:"Two sides of you look the same way today.", body:[
        "Tonight's reading gathers scattered thoughts into one clear line.",
        "The two sides of your mind look the same way today.",
        "If weighing which side is right has worn you out, you may rest now.",
        "The noise quiets and one clear sentence remains.",
        "Say the words you'd swallowed in hesitation — lightly, today.",
        "They will land more gently than you expect.",
        "Honesty doesn't break a bond; it ties it closer.",
        "A light joke loosens the heavy air.",
        "Today, listening makes you shine as much as speaking.",
        "Before sleep, write down the one line you wanted to say." ] } },
    cancer: {
      ko:{ teaser:"마음의 물결이 잔잔해진다.", body:[
        "오늘 당신의 별은 마음의 물결을 잔잔히 다독입니다.",
        "출렁이던 감정이 천천히 수면을 고르는 날이에요.",
        "누군가의 작은 안부가 오늘 당신을 데워줍니다.",
        "받은 온기는 움켜쥐지 말고 그대로 흘려보내요.",
        "돌보는 일에 지쳤다면 오늘은 당신을 돌볼 차례예요.",
        "약해 보이는 게 아니라 깊은 거라는 걸 잊지 마세요.",
        "집처럼 편한 자리에서 잠시 머물러도 괜찮아요.",
        "그리운 이름이 떠오르면 짧은 연락을 남겨도 좋아요.",
        "오늘의 다정함은 당신에게 가장 먼저 닿아야 합니다.",
        "잠들 무렵, 따뜻했던 순간 하나를 품고 눈 감으세요." ] },
      en:{ teaser:"The tide of your heart grows calm.", body:[
        "Tonight's reading calms the tide of your heart.",
        "Feelings that swayed slowly settle into stillness today.",
        "Someone's small hello will warm you.",
        "Don't clutch the warmth you receive — let it flow onward.",
        "If caring for others has tired you, today it's your turn.",
        "Remember: it isn't weakness, it's depth.",
        "It's fine to linger a while in a place that feels like home.",
        "If the name of someone you miss comes to mind, leave a short message.",
        "Today's tenderness should reach you first.",
        "As sleep nears, close your eyes holding one warm moment." ] } },
    leo: {
      ko:{ teaser:"빛내려 하지 않아도 이미 환하다.", body:[
        "오늘 당신의 별은 애쓰지 않아도 이미 환합니다.",
        "무언가를 증명해야 할 일이 없는 하루예요.",
        "큰 소리 대신 가만한 자신감이 주변을 밝힙니다.",
        "빛내려 들수록 빛은 오히려 옅어진다는 걸 기억하세요.",
        "당신이 머문 자리는 저절로 따뜻해집니다.",
        "칭찬을 기다리지 않아도 당신의 가치는 그대로예요.",
        "누군가의 그늘이 되어주는 일도 오늘은 빛입니다.",
        "자존심을 잠시 내려두면 더 큰 사람이 됩니다.",
        "당신의 너그러움이 오늘 누군가를 일으켜 세워요.",
        "오늘 밤, 굳이 증명하지 않은 자신을 아껴주세요." ] },
      en:{ teaser:"Bright already, without trying to shine.", body:[
        "Tonight's reading says you are already bright without trying.",
        "There is nothing you must prove today.",
        "A quiet confidence lights the room more than any loud voice could.",
        "Remember: the harder you try to shine, the dimmer it gets.",
        "Wherever you rest grows warm on its own.",
        "Your worth stays the same without waiting for praise.",
        "Offering someone shade is its own light today.",
        "Set your pride down a moment and you grow larger.",
        "Your generosity lifts someone back up today.",
        "Tonight, cherish the self that didn't need to prove anything." ] } },
    virgo: {
      ko:{ teaser:"작은 정돈이 큰 안심을 부른다.", body:[
        "오늘 당신의 별은 작은 정돈에서 큰 안심을 길어 올립니다.",
        "완벽 대신 '충분'으로 충분한 하루예요.",
        "하나만 제자리에 두어도 마음이 한결 가벼워집니다.",
        "빈틈을 메우려다 자신을 깎지 않아도 돼요.",
        "당신이 보는 결점은 대개 당신만 보는 것입니다.",
        "오늘은 해낸 것들의 목록을 먼저 헤아려 보세요.",
        "꼼꼼함은 결국 누군가를 향한 다정함이었어요.",
        "모든 걸 통제하지 않아도 세상은 잘 흘러갑니다.",
        "작은 쉼표 하나가 긴 문장을 살립니다.",
        "잠들기 전, 오늘의 당신에게 '잘했다'고 말해주세요." ] },
      en:{ teaser:"A small tidying brings deep ease.", body:[
        "Tonight's reading draws deep ease from a small tidying.",
        "Today, enough is enough; it needn't be perfect.",
        "Put one thing in its place and your mind grows lighter.",
        "You needn't carve yourself down to fill every gap.",
        "The flaw you see is usually one only you can see.",
        "Today, count what you have done first.",
        "Your attention to detail was, all along, kindness toward someone.",
        "The world keeps flowing even when you don't control it all.",
        "One small comma saves a long sentence.",
        "Before sleep, tell the self you were today: you did well." ] } },
    libra: {
      ko:{ teaser:"기울던 저울이 천천히 중심을 찾는다.", body:[
        "오늘 당신의 별은 기울던 저울에 중심을 돌려줍니다.",
        "양쪽을 다 헤아리느라 지쳤다면 잠시 멈춰도 돼요.",
        "오늘만큼은 저울을 당신 쪽으로 한 뼘 기울여 보세요.",
        "모두를 만족시키는 답은 원래 없는 것이었어요.",
        "당신의 마음도 똑같이 무게를 가질 자격이 있습니다.",
        "거절은 차가움이 아니라 솔직한 친절일 수 있어요.",
        "균형은 멈춰 있는 게 아니라 끊임없이 고르는 일이에요.",
        "작은 아름다움 하나가 오늘 하루를 정돈해 줍니다.",
        "망설임이 길어질 땐 마음이 더 끌리는 쪽을 믿어요.",
        "오늘 밤은 당신을 먼저 위한 선택 하나를 떠올려 보세요." ] },
      en:{ teaser:"A tilting scale finds its center, slowly.", body:[
        "Tonight's reading brings a tilting scale back to center.",
        "If weighing both sides wore you out, you may pause.",
        "Just for today, lean the scale a hand's width toward yourself.",
        "The answer that satisfies everyone never existed.",
        "Your own heart deserves to carry weight too.",
        "A no can be an honest kindness, not coldness.",
        "Balance isn't standing still; it's finding your center, again and again.",
        "One small beauty sets your whole day in order.",
        "When hesitation runs long, trust the side you lean toward.",
        "Tonight, recall one choice you made for yourself first." ] } },
    scorpio: {
      ko:{ teaser:"깊은 곳의 물이 맑아진다.", body:[
        "오늘 당신의 별은 깊은 곳의 물을 맑게 가라앉힙니다.",
        "오래 감춰둔 마음 하나를 가만히 풀어놓아도 좋은 날이에요.",
        "가라앉아 있던 것이 오늘은 빛을 받습니다.",
        "다 드러내지 않아도 한 겹쯤은 내려놓아 보세요.",
        "비밀을 지키는 힘은 그것을 놓을 줄 아는 데서 와요.",
        "당신의 진심은 약점이 아니라 깊이입니다.",
        "미워하던 마음 아래엔 사실 아끼는 마음이 있었어요.",
        "오늘의 솔직함이 관계를 더 단단히 묶어줍니다.",
        "어두운 물속에도 별빛은 끝내 닿습니다.",
        "잠들기 전, 무겁던 마음 한 조각을 내려놓고 숨을 쉬어요." ] },
      en:{ teaser:"The deep water clears.", body:[
        "Tonight's reading lets the deep water settle clear.",
        "It's a good day to quietly set down one long-hidden feeling.",
        "What had sunk catches the light today.",
        "You needn't reveal it all — just let one layer go.",
        "The strength to keep a secret comes from knowing how to release it.",
        "Your sincerity is not weakness, but depth.",
        "Beneath the feeling you called hate was, in truth, care.",
        "Today's honesty ties the bond tighter.",
        "Even in dark water, starlight reaches in the end.",
        "Before sleep, set down one heavy piece and breathe." ] } },
    sagittarius: {
      ko:{ teaser:"멀리 보던 눈이 가까운 길을 본다.", body:[
        "오늘 당신의 별은 멀리 보던 눈에 가까운 길을 비춥니다.",
        "떠나고 싶은 마음은 잠시 접어두어도 괜찮아요.",
        "오늘의 한 걸음이 그 먼 곳으로 이어지고 있어요.",
        "새 풍경은 꼭 멀리 있지 않습니다, 모퉁이 하나 너머일 수도.",
        "자유는 도망이 아니라 스스로 고른 방향이에요.",
        "가벼운 호기심 하나가 오늘 하루를 넓혀줍니다.",
        "약속을 지키는 일이 오늘은 모험만큼 빛나요.",
        "멀리 쏜 화살도 결국 지금의 손끝에서 출발합니다.",
        "조급한 큰 그림보다 또렷한 한 걸음을 믿어요.",
        "오늘 밤, 가고 싶은 곳 하나를 마음에 그려두세요." ] },
      en:{ teaser:"Eyes that look far find the nearby road.", body:[
        "Tonight's reading shows the nearby road to eyes that look far.",
        "The wish to leave may rest a while — that's all right.",
        "Today's single step is already leading toward that far place.",
        "New scenery isn't always distant; it may be just past one corner.",
        "Freedom isn't flight; it's a direction you chose.",
        "One light curiosity widens your whole day.",
        "Keeping a promise shines as bright as adventure today.",
        "Even an arrow shot far begins in this hand, now.",
        "Trust one clear step over an anxious grand plan.",
        "Tonight, picture one place you'd like to go." ] } },
    capricorn: {
      ko:{ teaser:"오래 쌓은 것이 조용히 단단해진다.", body:[
        "오늘 당신의 별은 오래 쌓아온 것을 조용히 단단하게 합니다.",
        "성과가 보이지 않아도 헛되지 않은 하루예요.",
        "묵묵한 오늘이 내일의 디딤돌이 됩니다.",
        "모든 걸음이 정상을 향할 필요는 없어요, 멈춤도 길입니다.",
        "당신의 성실은 누가 안 봐도 사라지지 않습니다.",
        "가끔은 짐을 내려놓아야 더 멀리 갈 수 있어요.",
        "스스로에게 인색했던 마음을 오늘은 풀어주세요.",
        "천천히 굳은 것이 가장 오래 버팁니다.",
        "책임감 옆에 다정함도 한 자리 내어주어요.",
        "잠들기 전, 여기까지 온 자신에게 고생했다 말해주세요." ] },
      en:{ teaser:"What you've built quietly grows solid.", body:[
        "Tonight's reading quietly strengthens what you've long built.",
        "Even with no visible result, today is not wasted.",
        "This steady day becomes tomorrow's foothold.",
        "Not every step must climb; a pause is also the path.",
        "Your diligence doesn't vanish just because no one watches.",
        "Sometimes you must set the load down to go farther.",
        "Today, soften the heart that has been stingy with yourself.",
        "What grows solid slowly endures the longest.",
        "Make room beside your duty for tenderness too.",
        "Before sleep, tell the self who came this far: well done." ] } },
    aquarius: {
      ko:{ teaser:"남다른 생각이 오늘은 길을 만든다.", body:[
        "오늘 당신의 별은 남다른 생각에 길을 내어줍니다.",
        "이상해 보일까 접어둔 생각이 있다면 한 번 꺼내보세요.",
        "누군가에겐 그것이 처음 보는 빛이 됩니다.",
        "다르다는 건 틀린 게 아니라 새롭다는 뜻이에요.",
        "무리에 섞이려 자신을 지우지 않아도 됩니다.",
        "멀찍이서 보는 당신의 시선이 오늘 도움이 돼요.",
        "차가워 보여도 당신 안엔 따뜻한 사람이 있어요.",
        "혼자만의 시간이 당신에겐 충전이지 외로움이 아니에요.",
        "작은 아이디어 하나를 오늘 가볍게 말해보세요.",
        "잠들기 전, 당신다움을 지운 적 없는 하루를 기뻐하세요." ] },
      en:{ teaser:"An unusual idea makes a road today.", body:[
        "Tonight's reading makes a road for the ideas that make you different.",
        "If you folded away a thought for fear it seemed strange, unfold it today.",
        "To someone, it becomes a light they've never seen.",
        "Different doesn't mean wrong; it means new.",
        "You needn't erase yourself to blend into the crowd.",
        "Your view from a little distance helps today.",
        "However cool you seem, a warm person lives inside you.",
        "Time alone recharges you; it isn't loneliness.",
        "Today, say one small idea out loud, lightly.",
        "Before sleep, be glad for a day when you never erased yourself." ] } },
    pisces: {
      ko:{ teaser:"흐릿하던 마음에 윤곽이 잡힌다.", body:[
        "오늘 당신의 별은 흐릿하던 마음에 윤곽을 그려줍니다.",
        "꿈과 현실 사이를 떠돌았다면 이제 한쪽에 발을 디뎌요.",
        "디딘 그 자리가 생각보다 단단히 당신을 받쳐줍니다.",
        "다정함이 많아 잘 휘둘리던 마음에 오늘은 테두리가 생겨요.",
        "모두를 품으려다 자신을 잃지 않아도 됩니다.",
        "눈물 한 방울도 당신에겐 정직한 언어예요.",
        "상상은 도피가 아니라 당신만의 깊은 우물입니다.",
        "오늘은 거절해도 미안해하지 않는 연습을 해보세요.",
        "흐르는 대로 두되, 키는 당신이 쥐고 있어요.",
        "잠들기 전, 부드러운 당신을 약점이라 부르지 마세요." ] },
      en:{ teaser:"A blurred feeling finds its outline.", body:[
        "Tonight's reading draws an outline around a blurred heart.",
        "If you've drifted between dreams and waking life, set one foot down now.",
        "That ground holds you more firmly than you expected.",
        "A heart easily swayed by its own tenderness gains a boundary today.",
        "You needn't lose yourself trying to hold everyone.",
        "Even a single tear is an honest language for you.",
        "Imagination isn't escape; it's your own deep well.",
        "Today, practice saying no without an apology.",
        "Let things flow, but keep your hand on the rudder.",
        "Before sleep, don't call your softness a weakness." ] } },
  },
};
