  /* ===== i18n 사전 — 새 레벨/트릭은 여기에 키만 추가하면 다국어 자동 적용 ===== */
  const I18N = {
    ko: {
      title:"밤바다",
      subtitle:"",
      reset:"↻ 처음부터",
      confirm:"확인",
      placeholder:"암호 입력",
      ok:"맞다. 다음으로.",
      bad:"아니다. 다시.",
      gaugeInit:"기울기: —",
      gaugePrefix:"기울기: ",
      sensor:"📲 탭해서 센서 켜기 (iOS)",
      l1tag:"출항 · 어두운 항구",
      l1riddle:"🌑 누군가를 배웅하러 왔다. 허나 항구는 아직 어둠.\n빛은, 가만히 오래 닿아야 든다.",
      l1press:"꾹 — 눌러본다",
      l1reveal:"달빛",
      l1hint:"힌트: 화면을 *길게* 눌러라.",
      l2tag:"출항 · 젖은 항해일지",
      l2riddle:"📜 진실은 깨알처럼 작다.\n두 손가락으로, 키워서 읽어라.",
      l2before:"파도가 밤새 종이를 적신다. 글씨는 번지고, 대부분은 의미가 없다.",
      l2tiny:"암호는 등대",
      l2after:"그래도 한 줄, 아주 작은 한 줄만은 끝까지 남았다.",
      l2hint:"힌트: 회색 글상자를 *핀치 줌*으로 확대해.",
      l3tag:"출항 · 키를 잡고",
      l3riddle:"📱 똑바로 보면 안 보인다.\n폰을 옆으로 기울여, 수면을 맞춰라.",
      l3secret:"수평선",
      l3hint:"힌트: 폰을 좌우로 약 45° *기울이면* 드러난다.",
      l4tag:"출항 · 돛을 펴다",
      l4riddle:"🌬️ 이제 정말 떠난다. 돛이 늘어져 있다 —\n숨을 보태야, 배가 나아간다.",
      l4hint:"힌트: 폰 마이크에 대고 *후— 불어라.* (돛이 차오르면 출항)",
      l4windPrefix:"바람: ",
      l4windBtn:"🎤 마이크 켜고 출항 준비",
      l4set:"돛이 부푼다… 출항 🌊",
      l4oar:"🚣 노 저어 나아가기 (탭 반복)",
      l4oarPrefix:"노 젓기: ",
      l4oarSet:"노를 저어 나아간다… 출항 🌊",
      l5tag:"출항 · 첫 물길",
      l5riddle:"✦ 어둠뿐인 바다. 길잡이는 하늘에 있다.\n흩어진 별을 손가락으로 이어, 길을 그려라.",
      l5hint:"힌트: 손가락으로 별을 *모두 잇도록* 그어라. (안 되면 ‘다시 긋기’)",
      l5clear:"↺ 다시 긋기",
      l5reveal:"북극성",
      l6tag:"안개 1 · 등불 감싸기",
      l6riddle:"🌫️ 안개가 짙다. 작은 등불 하나가 바람에 휘청인다.\n두 손가락으로 감싸, 불꽃을 지켜라.",
      l6hint:"힌트: 두 손가락을 등불 양옆에 모아 *감싸라.* (한 손이면 아래 ‘가리기’를 길게 눌러)",
      l6shelterPrefix:"보호: ",
      l6shelterBtn:"🤚 한 손으로 가리기 (길게)",
      l6set:"불꽃이 잦아들지 않는다… 곁에 온기가 머문다 🕯️",
      l7tag:"폭풍 1 · 노 젓기",
      l7riddle:"🌊 파도가 거세다. 혼자선 못 건넌다.\n동행과 박자를 맞춰, 좌우로 번갈아 노를 저어라.",
      l7hint:"힌트: 빛나는 쪽 노를 *좌우 번갈아* 눌러 저어라.",
      l7rowPrefix:"전진: ",
      l7set:"폭풍을 넘었다… 멀리, 별이 보인다 ✦",
      doneTitle:"항해 🌅",
      doneBody:"달빛과 별, 바람과 등불, 그리고 폭풍을 넘어.<br>밤바다 한가운데, 잠시 숨을 고른다.",
      doneEnd:"— 다음 항해(작별)는 곧 —",
      answers:["달빛","등대","수평선","북극성"]
    },
    en: {
      title:"Night Sea",
      subtitle:"",
      reset:"↻ Restart",
      confirm:"Enter",
      placeholder:"passcode",
      ok:"Correct. Onward.",
      bad:"No. Try again.",
      gaugeInit:"tilt: —",
      gaugePrefix:"tilt: ",
      sensor:"📲 Tap to enable sensor (iOS)",
      l1tag:"SET SAIL · the dark harbor",
      l1riddle:"🌑 You came to see someone off — but the harbor is still dark.\nLight comes only to what waits, long and still.",
      l1press:"press — and hold",
      l1reveal:"moonlight",
      l1hint:"Hint: *press and hold* the screen.",
      l2tag:"SET SAIL · the soaked logbook",
      l2riddle:"📜 The truth is fine as a grain.\nPinch with two fingers to read it.",
      l2before:"Waves soak the paper all night. The ink bleeds; most of it means nothing.",
      l2tiny:"the passcode is lighthouse",
      l2after:"Yet one line, the smallest line, survived to the end.",
      l2hint:"Hint: *pinch-zoom* the gray box.",
      l3tag:"SET SAIL · take the helm",
      l3riddle:"📱 Look straight on and you see nothing.\nTilt your phone sideways, level it to the water.",
      l3secret:"horizon",
      l3hint:"Hint: tilt the phone left/right ~45° to reveal it.",
      l4tag:"SET SAIL · raise the sail",
      l4riddle:"🌬️ Now you truly leave. The sail hangs limp —\nadd your breath, and the boat moves.",
      l4hint:"Hint: *blow* into your phone's mic. (Fill the sail to set sail.)",
      l4windPrefix:"wind: ",
      l4windBtn:"🎤 Enable mic & prepare to sail",
      l4set:"The sail swells… setting sail 🌊",
      l4oar:"🚣 Row out (tap repeatedly)",
      l4oarPrefix:"rowing: ",
      l4oarSet:"You row out… setting sail 🌊",
      l5tag:"SET SAIL · the first channel",
      l5riddle:"✦ Nothing but dark sea. The guide is in the sky.\nConnect the scattered stars with your finger to draw the way.",
      l5hint:"Hint: drag to *connect all the stars*. (stuck? tap ‘redraw’)",
      l5clear:"↺ redraw",
      l5reveal:"polaris",
      l6tag:"FOG 1 · shelter the flame",
      l6riddle:"🌫️ The fog is thick. A small lantern wavers in the wind.\nCup it with two fingers and keep the flame alive.",
      l6hint:"Hint: bring two fingers around the lantern to *shelter* it. (one hand? press & hold ‘shield’ below)",
      l6shelterPrefix:"shelter: ",
      l6shelterBtn:"🤚 shield with one hand (hold)",
      l6set:"The flame holds steady… a warmth stays beside you 🕯️",
      l7tag:"STORM 1 · row",
      l7riddle:"🌊 The waves are fierce — you can't cross alone.\nMatch your companion's rhythm: pull the oars, left and right in turn.",
      l7hint:"Hint: tap the *glowing* oar, alternating left and right.",
      l7rowPrefix:"progress: ",
      l7set:"Through the storm… far off, stars appear ✦",
      doneTitle:"Voyage 🌅",
      doneBody:"Moonlight and stars, wind and lantern, and through the storm.<br>Mid–night-sea, you catch your breath.",
      doneEnd:"— the next voyage (farewell) comes soon —",
      answers:["moonlight","lighthouse","horizon","polaris"]
    }
  };
