  /* ===== i18n 사전 — 새 레벨/트릭은 여기에 키만 추가하면 다국어 자동 적용 ===== */
  const I18N = {
    ko: {
      title:"밤바다",
      subtitle:"",
      reset:"↻ 처음부터",
      menu:"목록",
      gatePrompt:"처음 오셨나요?", gateYes:"네 — 첫 항해를 시작할게요", gateNo:"아니오 — 항구로 갈게요",
      confirm:"확인",
      placeholder:"암호 입력",
      ok:"맞다. 다음으로.",
      bad:"아니다. 다시.",
      gaugeInit:"기울기: —",
      gaugePrefix:"기울기: ",
      sensor:"📲 탭해서 센서 켜기 (iOS)",
      l1tag:"출항 · 어두운 항구",
      l1riddle:"🌑 누군가를 배웅하러 왔다. 허나 항구는 아직 어둠.\n빛은, 가만히 오래 닿아야 든다.",
      l1press:"꾹 — 눌러본다",
      l1reveal:"달빛",
      l1hint:"힌트: 화면을 *길게* 눌러라.",
      l2tag:"출항 · 젖은 항해일지",
      l2riddle:"📜 진실은 깨알처럼 작다.\n두 손가락으로, 키워서 읽어라.",
      l2before:"파도가 밤새 종이를 적신다. 글씨는 번지고, 대부분은 의미가 없다.",
      l2tiny:"암호는 등대",
      l2after:"그래도 한 줄, 아주 작은 한 줄만은 끝까지 남았다.",
      l2hint:"힌트: 회색 글상자를 *핀치 줌*으로 확대해.",
      l3tag:"출항 · 키를 잡고",
      l3riddle:"📱 똑바로 보면 안 보인다.\n폰을 옆으로 기울여, 수면을 맞춰라.",
      l3secret:"수평선",
      l3hint:"힌트: 폰을 좌우로 약 45° *기울이면* 드러난다.",
      l3fbhint:"센서가 없으면 — 슬라이더를 *끝까지 밀어* 기울여라.",
      l4tag:"출항 · 돛을 펴다",
      l4riddle:"🌬️ 이제 정말 떠난다. 돛이 늘어져 있다 —\n숨을 보태야, 배가 나아간다.",
      l4hint:"힌트: 폰 마이크에 대고 *후— 불어라.* (돛이 차오르면 출항)",
      l4windPrefix:"바람: ",
      l4windBtn:"🎤 마이크 켜고 출항 준비",
      l4set:"돛이 부푼다… 출항 🌊",
      l4oar:"🚣 노 저어 나아가기 (탭 반복)",
      l4oarPrefix:"노 젓기: ",
      l4oarSet:"노를 저어 나아간다… 출항 🌊",
      l5tag:"출항 · 첫 물길",
      l5riddle:"✦ 어둠뿐인 바다. 길잡이는 하늘에 있다.\n흩어진 별을 손가락으로 이어, 길을 그려라.",
      l5hint:"힌트: 손가락으로 별을 *모두 잇도록* 그어라. (안 되면 ‘다시 긋기’)",
      l5clear:"↺ 다시 긋기",
      l5reveal:"북극성",
      l6tag:"안개 1 · 등불 감싸기",
      l6riddle:"🌫️ 안개가 짙다. 작은 등불 하나가 바람에 휘청인다.\n두 손가락으로 감싸, 불꽃을 지켜라.",
      l6hint:"힌트: 두 손가락을 등불 양옆에 모아 *감싸라.* (한 손이면 아래 ‘가리기’를 길게 눌러)",
      l6shelterPrefix:"보호: ",
      l6shelterBtn:"🤚 한 손으로 가리기 (길게)",
      l6set:"불꽃이 잦아들지 않는다… 곁에 온기가 머문다 🕯️",
      l7tag:"폭풍 1 · 노 젓기",
      l7riddle:"🌊 파도가 거세다. 혼자선 못 건넌다.\n둘의 박자로 — 좌우로 번갈아 노를 저어라.",
      l7hint:"힌트: 빛나는 쪽 노를 *좌우 번갈아* 눌러 저어라.",
      l7rowPrefix:"전진: ",
      l7set:"폭풍을 넘었다… 멀리, 별이 보인다 ✦",
      l8tag:"작별 · 졸업 연주",
      l8hint:"힌트: 버튼을 *지그시 누른 채로* — 손을 떼지 말고 끝까지.",
      l8btn:"🤲 지그시 — 끝까지 누르고 있기",
      l8lines:["마지막 불빛을, 두 손으로 가만히 감싼다.","건너편으로 — 등불을 건넨다.","빈 배의 뱃머리를, 돌아오는 쪽으로 돌린다.","멀어지며, 마지막으로 숨을 보탠다."],
      l8end:"잘 가. 이쪽은 내가 지킬게.",
      doneTitle:"항해 🌅",
      doneBody:"닿았다. 등불은 건너편에서 깜빡이고,<br>빈 배는, 왔던 쪽으로 — 혼자 돌아온다.",
      doneEnd:"— 첫 항해 끝 · fin —",
      sc_tutorial:"첫 항해 — 밤바다", hubTitle:"항구 · 떠날 채비",
      sc_snow:"첫눈 호수 — 노견을 건너다",
      snow1tag:"첫눈 호수 · 떨고 있는", snow1riddle:"❄️ 첫눈이 내린 호수. 늙은 개가 가만히 떨고 있다.\n곁에 가만히, 오래 손을 대어라.", snow1press:"가만히 — 손을 대본다", snow1reveal:"온기", snow1hint:"힌트: 화면을 *길게* 눌러 온기를 나눠라.", snow_a1:"온기",
      snow2tag:"첫눈 호수 · 잔물결", snow2riddle:"🚣 개가 배에 올랐다. 잔잔한 호수를 건너자.\n좌우로 번갈아, 천천히 노를 저어라.", snow2hint:"힌트: 빛나는 쪽 노를 *좌우 번갈아* 눌러 저어라.",
      snowDoneTitle:"건너편 ❄️",
      snowDoneBody:"늙은 개는 뱃머리에 턱을 괴고, 오는 내내 너를 보고 있었다.<br>마른 땅에 발을 디딘 개는 — 건너편에서 딱 한 번 돌아봤다. 오래 함께 산 사람을 볼 때의 눈으로.<br>「이제 안 추울 거야.」",
      snowCoda:"배를 돌리는데, 바닥에 목줄이 남아 있었다. 풀린 게 아니라 — 두고 간 것이었다. 너에게.",
      snowDoneEnd:"— 첫눈 호수 · fin —",
      sc_dawn:"새벽 강 — 아이를 건너다",
      dawnTag:"새벽 강 · 나란히", dawnRiddle:"🌫️ 안개 걷히는 새벽 강. 이사 가는 아이가 배에 올랐다.\n아이와 박자를 맞춰 — 두 노를 *동시에* 저어라.", dawnHint:"힌트: 양쪽 노를 *함께* 눌러라(두 손가락). 한 손이면 아래 ‘함께 젓기’를 두드려.",
      rpPrefix:"전진: ", rpSet:"강을 건넜다… 아이가 앞을 본다 🌅", rpSyncBtn:"🤲 함께 젓기 (탭)",
      dawnDoneTitle:"건너편 🌅",
      dawnDoneBody:"아이는 마른 땅에 내리자마자 — 앞으로 달려갔다. 한 번도 돌아보지 않고.<br>그게 좋은 거였다. 돌아볼 게 없다는 건, 가는 곳이 더 좋다는 뜻이니까.<br>「거기서도 잘 자라렴.」",
      dawnCoda:"발치에 종이배 한 척이 떠 있었다. 서툴게 접은 — 너를 흉내 낸 것이었다. 두고 간 게 아니라, 만들어 두고 간 것.",
      dawnDoneEnd:"— 새벽 강 · fin —",
      warmPrefix:"온기: ", warmSet:"떨림이 멎었다… 배에 오른다 🐕",
      endStay:"이쪽은 — 그대로 남아, 불을 켜 둔다.",
      shareTitle:"오늘 밤, 누군가가 무사히 건넜습니다.", shareBody:"건너편엔 등불 하나. 다음 사람의 첫 밤이 그 불로 밝습니다.",
      shareBtn:"🕯️ 등불을 다음 사람에게 →", shareText:"누군가를 건너편까지 — 밤바다를 건너보세요.", backToHarbor:"항구로 돌아가기",
      l1answer:"달빛", l2answer:"등대", l3answer:"수평선", l5answer:"북극성",
      answers:["달빛","등대","수평선","북극성"]
    },
    en: {
      title:"Night Sea",
      subtitle:"",
      reset:"↻ Restart",
      menu:"Menu",
      gatePrompt:"First time here?", gateYes:"Yes — start the voyage", gateNo:"No — take me to the harbor",
      confirm:"Enter",
      placeholder:"passcode",
      ok:"Correct. Onward.",
      bad:"No. Try again.",
      gaugeInit:"tilt: —",
      gaugePrefix:"tilt: ",
      sensor:"📲 Tap to enable sensor (iOS)",
      l1tag:"SET SAIL · the dark harbor",
      l1riddle:"🌑 You came to see someone off — but the harbor is still dark.\nLight comes only to what waits, long and still.",
      l1press:"press — and hold",
      l1reveal:"moonlight",
      l1hint:"Hint: *press and hold* the screen.",
      l2tag:"SET SAIL · the soaked logbook",
      l2riddle:"📜 The truth is fine as a grain.\nPinch with two fingers to read it.",
      l2before:"Waves soak the paper all night. The ink bleeds; most of it means nothing.",
      l2tiny:"the passcode is lighthouse",
      l2after:"Yet one line, the smallest line, survived to the end.",
      l2hint:"Hint: *pinch-zoom* the gray box.",
      l3tag:"SET SAIL · take the helm",
      l3riddle:"📱 Look straight on and you see nothing.\nTilt your phone sideways, level it to the water.",
      l3secret:"horizon",
      l3hint:"Hint: tilt the phone left/right ~45° to reveal it.",
      l3fbhint:"No sensor? *Slide it all the way* to tilt and reveal.",
      l4tag:"SET SAIL · raise the sail",
      l4riddle:"🌬️ Now you truly leave. The sail hangs limp —\nadd your breath, and the boat moves.",
      l4hint:"Hint: *blow* into your phone's mic. (Fill the sail to set sail.)",
      l4windPrefix:"wind: ",
      l4windBtn:"🎤 Enable mic & prepare to sail",
      l4set:"The sail swells… setting sail 🌊",
      l4oar:"🚣 Row out (tap repeatedly)",
      l4oarPrefix:"rowing: ",
      l4oarSet:"You row out… setting sail 🌊",
      l5tag:"SET SAIL · the first channel",
      l5riddle:"✦ Nothing but dark sea. The guide is in the sky.\nConnect the scattered stars with your finger to draw the way.",
      l5hint:"Hint: drag to *connect all the stars*. (stuck? tap ‘redraw’)",
      l5clear:"↺ redraw",
      l5reveal:"polaris",
      l6tag:"FOG 1 · shelter the flame",
      l6riddle:"🌫️ The fog is thick. A small lantern wavers in the wind.\nCup it with two fingers and keep the flame alive.",
      l6hint:"Hint: bring two fingers around the lantern to *shelter* it. (one hand? press & hold ‘shield’ below)",
      l6shelterPrefix:"shelter: ",
      l6shelterBtn:"🤚 shield with one hand (hold)",
      l6set:"The flame holds steady… a warmth stays beside you 🕯️",
      l7tag:"STORM 1 · row",
      l7riddle:"🌊 The waves are fierce — you can't cross alone.\nTwo find the rhythm: pull the oars, left and right in turn.",
      l7hint:"Hint: tap the *glowing* oar, alternating left and right.",
      l7rowPrefix:"progress: ",
      l7set:"Through the storm… far off, stars appear ✦",
      l8tag:"FAREWELL · the recital",
      l8hint:"Hint: *press and hold* — keep holding, all the way to the end.",
      l8btn:"🤲 hold gently — to the end",
      l8lines:["Cup the last light, gently, in both hands.","Across the water — hand the lantern over.","Turn the empty boat's bow back toward home.","As you drift away, add one last breath to the sail."],
      l8end:"Go well. I'll keep this side.",
      doneTitle:"Voyage 🌅",
      doneBody:"It reached. The lantern blinks on the far shore,<br>and the empty boat turns home — alone.",
      doneEnd:"— end of the first voyage · fin —",
      sc_tutorial:"First Voyage — Night Sea", hubTitle:"The Harbor",
      sc_snow:"Snow Lake — ferry the old dog",
      snow1tag:"SNOW LAKE · the shivering one", snow1riddle:"❄️ A lake under first snow. An old dog shivers, still.\nRest your hand beside it — long and quiet.", snow1press:"rest — your hand", snow1reveal:"warmth", snow1hint:"Hint: *press and hold* to share warmth.", snow_a1:"warmth",
      snow2tag:"SNOW LAKE · still ripples", snow2riddle:"🚣 The dog has boarded. Cross the still lake.\nPull the oars, left and right in turn.", snow2hint:"Hint: tap the *glowing* oar, alternating.",
      snowDoneTitle:"The Far Shore ❄️",
      snowDoneBody:"The old dog rested its chin on the bow, watching you the whole way across.<br>Stepping onto dry ground, it looked back — just once. With the eyes of someone you've lived beside for years.<br>\"You won't be cold now.\"",
      snowCoda:"As you turn the boat, a leash lay on the floor. Not slipped loose — left behind. For you.",
      snowDoneEnd:"— Snow Lake · fin —",
      sc_dawn:"Dawn River — ferry the child",
      dawnTag:"DAWN RIVER · side by side", dawnRiddle:"🌫️ Dawn river, the fog lifting. The child who's moving away has boarded.\nMatch the child's rhythm — pull both oars *together*.", dawnHint:"Hint: press both oars *at once* (two fingers). One hand? tap ‘row together’ below.",
      rpPrefix:"progress: ", rpSet:"Across the river… the child looks ahead 🌅", rpSyncBtn:"🤲 row together (tap)",
      dawnDoneTitle:"The Far Shore 🌅",
      dawnDoneBody:"The moment the child touched dry ground — they ran ahead. Without looking back, not once.<br>That was the good kind. Nothing to look back for means somewhere better is waiting.<br>\"Grow well over there, too.\"",
      dawnCoda:"A paper boat drifted at your feet. Clumsily folded — made in your likeness. Not left behind, but made, and left for you.",
      dawnDoneEnd:"— Dawn River · fin —",
      warmPrefix:"warmth: ", warmSet:"The shivering stops… it climbs aboard 🐕",
      endStay:"This side — someone stays, keeps the light.",
      shareTitle:"Tonight, someone made it across.", shareBody:"On the far side, one lantern. It will light the next person's first night.",
      shareBtn:"🕯️ Pass the lantern on →", shareText:"Carry someone across the night sea.", backToHarbor:"Back to the harbor",
      l1answer:"moonlight", l2answer:"lighthouse", l3answer:"horizon", l5answer:"polaris",
      answers:["moonlight","lighthouse","horizon","polaris"]
    }
  };
