  /* ===== i18n 사전 — 새 레벨/트릭은 여기에 키만 추가하면 다국어 자동 적용 ===== */
  const I18N = {
    ko: {
      title:"건너편",
      subtitle:"",
      reset:"↻ 처음부터",
      menu:"목록",
      gatePrompt:"처음 오셨나요?", gateYes:"네 — 처음부터 시작할게요", gateNo:"아니오 — 길목으로 갈게요",
      confirm:"확인",
      placeholder:"암호 입력",
      ok:"맞다. 다음으로.",
      bad:"아니다. 다시.",
      gaugeInit:"기울기: —",
      gaugePrefix:"기울기: ",
      sensor:"📲 탭해서 센서 켜기 (iOS)",
      l1tag:"출항 · 어두운 항구",
      l1riddle:"🌑 누군가를 배웅하러 왔다. 허나 항구는 아직 어둠.\n빛은, 가만히 오래 닿아야 든다.",
      l1press:"꾹 — 눌러본다",
      l1reveal:"달빛",
      l1hint:"힌트: 화면을 *길게* 눌러라.",
      l2tag:"출항 · 젖은 항해일지",
      l2riddle:"📜 진실은 깨알처럼 작다.\n두 손가락으로, 키워서 읽어라.",
      l2before:"파도가 밤새 종이를 적신다. 글씨는 번지고, 대부분은 의미가 없다.",
      l2tiny:"암호는 등대",
      l2after:"그래도 한 줄, 아주 작은 한 줄만은 끝까지 남았다.",
      l2hint:"힌트: 회색 글상자를 *핀치 줌*으로 확대해.",
      l3tag:"출항 · 키를 잡고",
      l3riddle:"📱 똑바로 보면 안 보인다.\n폰을 옆으로 기울여, 수면을 맞춰라.",
      l3secret:"수평선",
      l3hint:"힌트: 폰을 좌우로 약 45° *기울이면* 드러난다.",
      l3fbhint:"센서가 없으면 — 슬라이더를 *끝까지 밀어* 기울여라.",
      l4tag:"출항 · 돛을 펴다",
      l4riddle:"🌬️ 이제 정말 떠난다. 돛이 늘어져 있다 —\n숨을 보태야, 배가 나아간다.",
      l4hint:"힌트: 폰 마이크에 대고 *후— 불어라.* (돛이 차오르면 출항)",
      l4windPrefix:"바람: ",
      l4windBtn:"🎤 마이크 켜고 출항 준비",
      l4set:"돛이 부푼다… 출항 🌊",
      l4oar:"🚣 노 저어 나아가기 (탭 반복)",
      l4oarPrefix:"노 젓기: ",
      l4oarSet:"노를 저어 나아간다… 출항 🌊",
      l5tag:"출항 · 첫 물길",
      l5riddle:"✦ 어둠뿐인 바다. 길잡이는 하늘에 있다.\n흩어진 별을 손가락으로 이어, 길을 그려라.",
      l5hint:"힌트: 손가락으로 별을 *모두 잇도록* 그어라. (안 되면 ‘다시 긋기’)",
      l5clear:"↺ 다시 긋기",
      l5reveal:"북극성",
      l6tag:"안개 1 · 등불 감싸기",
      l6riddle:"🌫️ 안개가 짙다. 작은 등불 하나가 바람에 휘청인다.\n두 손가락으로 감싸, 불꽃을 지켜라.",
      l6hint:"힌트: 두 손가락을 등불 양옆에 모아 *감싸라.* (한 손이면 아래 ‘가리기’를 길게 눌러)",
      l6shelterPrefix:"보호: ",
      l6shelterBtn:"🤚 한 손으로 가리기 (길게)",
      l6set:"불꽃이 잦아들지 않는다… 곁에 온기가 머문다 🕯️",
      l7tag:"폭풍 1 · 노 젓기",
      l7riddle:"🌊 파도가 거세다. 혼자선 못 건넌다.\n둘의 박자로 — 좌우로 번갈아 노를 저어라.",
      l7hint:"힌트: 빛나는 쪽 노를 *좌우 번갈아* 눌러 저어라.",
      l7rowPrefix:"전진: ",
      l7set:"폭풍을 넘었다… 멀리, 별이 보인다 ✦",
      l8tag:"작별 · 졸업 연주",
      l8hint:"힌트: 버튼을 *지그시 누른 채로* — 손을 떼지 말고 끝까지.",
      l8btn:"🤲 지그시 — 끝까지 누르고 있기",
      l8lines:["마지막 불빛을, 두 손으로 가만히 감싼다.","건너편으로 — 등불을 건넨다.","빈 배의 뱃머리를, 돌아오는 쪽으로 돌린다.","멀어지며, 마지막으로 숨을 보탠다."],
      l8end:"잘 가. 이쪽은 내가 지킬게.",
      doneTitle:"항해 🌅",
      doneBody:"닿았다. 등불은 건너편에서 깜빡이고,<br>빈 배는, 왔던 쪽으로 — 혼자 돌아온다.",
      doneEnd:"— 첫 항해 끝 · fin —",
      sc_tutorial:"첫 밤 — 손을 배우다", hubTitle:"길목",
      sc_snow:"첫눈 호수 — 노견을 건너다",
      snow1tag:"첫눈 호수 · 떨고 있는", snow1riddle:"❄️ 첫눈이 내린 호수. 늙은 개가 가만히 떨고 있다.\n곁에 가만히, 오래 손을 대어라.", snow1press:"가만히 — 손을 대본다", snow1reveal:"온기", snow1hint:"힌트: 화면을 *길게* 눌러 온기를 나눠라.", snow_a1:"온기",
      snow2tag:"첫눈 호수 · 잔물결", snow2riddle:"🚣 개가 배에 올랐다. 잔잔한 호수를 건너자.\n좌우로 번갈아, 천천히 노를 저어라.", snow2hint:"힌트: 빛나는 쪽 노를 *좌우 번갈아* 눌러 저어라.",
      snowDoneTitle:"건너편 ❄️",
      snowDoneBody:"늙은 개는 뱃머리에 턱을 괴고, 오는 내내 너를 보고 있었다.<br>마른 땅에 발을 디딘 개는 — 건너편에서 딱 한 번 돌아봤다. 오래 함께 산 사람을 볼 때의 눈으로.<br>「이제 안 추울 거야.」",
      snowCoda:"배를 돌리는데, 바닥에 목줄이 남아 있었다. 풀린 게 아니라 — 두고 간 것이었다. 너에게.",
      snowDoneEnd:"— 첫눈 호수 · fin —",
      sc_dawn:"새벽 강 — 아이를 건너다",
      dawnTag:"새벽 강 · 나란히", dawnRiddle:"🌫️ 안개 걷히는 새벽 강. 이사 가는 아이가 배에 올랐다.\n아이와 박자를 맞춰 — 두 노를 *동시에* 저어라.", dawnHint:"힌트: 양쪽 노를 *함께* 눌러라(두 손가락). 한 손이면 아래 ‘함께 젓기’를 두드려.",
      rpPrefix:"전진: ", rpSet:"강을 건넜다… 아이가 앞을 본다 🌅", rpSyncBtn:"🤲 함께 젓기 (탭)",
      foldTag:"새벽 강 · 종이배", foldRiddle:"🌫️ 떠나는 아이에게 줄 게 없다. 강가에 남은 낡은 종이 한 장뿐.\n손끝으로 천천히, *쓸어* 접어 — 작은 배를 만들어 줘.", foldHint:"힌트: 종이를 *쓸어서* 한 번씩 접어라 (세 번).",
      foldPrefix:"접기: ", foldSet:"작은 배가 완성됐다 🛶",
      dawnDoneTitle:"건너편 🌅",
      dawnDoneBody:"아이는 마른 땅에 내리자마자 — 앞으로 달려갔다. 한 번도 돌아보지 않고.<br>그게 좋은 거였다. 돌아볼 게 없다는 건, 가는 곳이 더 좋다는 뜻이니까.<br>「거기서도 잘 자라렴.」",
      dawnCoda:"발치에 종이배 한 척이 떠 있었다. 네가 접어준 것보다 작고 서툰 — 너를 흉내 낸 것이었다. 두고 간 게 아니라, 만들어 두고 간 것.",
      dawnDoneEnd:"— 새벽 강 · fin —",
      sc_lantern:"등불 항구 — 잊혀가는 이를 건너다",
      emberTag:"등불 항구 · 불씨", emberRiddle:"🪔 등불 가득한 항구. 한 사람의 기억이 꺼져 간다.\n불씨를 — 손 떼지 말고, 천천히 — 빈 등불로 옮겨라.", emberHint:"힌트: 불씨를 *누른 채로 천천히* 끌어가라. 손을 떼면 꺼진다.",
      emberPrefix:"옮기는 중: ", emberSet:"빈 등불에 불이 들었다 🪔", emberOut:"불씨가 꺼졌다… 다시",
      lanternDoneTitle:"건너편 🪔",
      lanternDoneBody:"건너편에 닿자, 그 사람은 너를 보았다 — 그러나 알아보지 못했다. 이미 너무 많이 잊은 것이다.<br>그래도 괜찮았다. 잊는 쪽이 더 가벼우니까.<br>「잊혀도, 여기 한 칸은 비워둘게.」",
      lanternCoda:"돌아오는 항구, 등불 하나가 새로 켜져 있었다. 이름표는 비어 있고 — 네가 옮겨다 둔 불이었다. 잊혀도, 자리는 남는다.",
      lanternDoneEnd:"— 등불 항구 · fin —",
      sc_reunion:"재회 — 건너편의 한 칸",
      reunionTag:"재회 · 두 불빛", reunionRiddle:"✨ 먼저 건너간 이가, 오래 기다리고 있다.\n네 불빛을 — 서두르지 말고, 아주 천천히 — 그 곁으로.", reunionHint:"힌트: 불빛을 *누른 채로 아주 천천히* 끌어가라. 서두르거나 떼면 멈춘다.",
      reunionPrefix:"다가가는 중: ", reunionSet:"두 불빛이 닿았다 ✨", reunionOut:"멈췄다… 다시, 천천히",
      reunionDoneTitle:"건너편 ✨",
      reunionDoneBody:"배가 닿는다. 흔들림이 멎는다.<br>그가 내린다. 서두르지 않고.",
      reunionSeq:["건너편에 불빛 하나.","작다. 오래된 불이다.","그가 멈춰 선다.","…저 불을 안다.","한 걸음.","불빛이 흔들린다. 마주 본 듯이.","또 한 걸음.","멀리서, 누군가 일어선다.","오래 앉아 있던 자리에서.","그가 빨라진다.","부르지 않는다. 부를 필요가 없다.","두 불빛 사이가 좁아진다.","좁아지고,","좁아지고,","닿는다.","한 칸 비워두었던 자리.","이번엔 그 자리가, 그를 기다린 거였다.","두 불빛이 하나가 된다.","더 환하지 않다. 다만 따뜻하다.","뱃사공은 보고 있다.","다 건너간 것을 확인할 때까지.","그리고 조용히, 고개를 끄덕인다."],
      reunionCoda:"빈 배의 뱃머리를 돌린다.",
      reunionDoneEnd:"늘 먼저 와 있고, 떠난 뒤에도 남아 있다. — fin —",
      libraryLabel:"이야기", storyTitle:"건너간 자리", storyTag:"단편 소설",
      seriesBoatman:"뱃사공", seriesMemory:"측량가", seriesTower:"퀴즈 타워", comingLabel:"곧 펼쳐집니다",
      towerProgress:"현재", hintCta:"막혔나요? 💡 힌트",
      towerFloor1:"1층", sc_tower_a4:"1-4 · 버팀", sc_tower_a6:"1-6 · 외줄",
      qtReveal:"✦ 길이 드러난다",
      holdPadLabel:"닻 패드",
      holdLockLabel:"접근성 잠금",
      holdPrefix:"버팀: ",
      holdDecayPrefix:"풀림: ",
      holdSet:"잡은 길이 머문다 ✦",
      ropeSensorBtn:"기울임 켜기",
      ropeLeftBtn:"왼쪽 균형",
      ropeRightBtn:"오른쪽 균형",
      ropePrefix:"별 ",
      ropeReadyPrefix:"별 완료 · 중심: ",
      ropeSet:"외줄이 이어졌다 ✦",
      qt1pTag:"퀴즈 타워 1층 · 긴 숨", qt1pRiddle:"잠든 문은 두드림보다 오래 머무는 손을 기억한다.", qt1pPress:"가만히 오래 닿기", qt1pHint:"힌트: 손을 떼지 말고 기다려라.", qt1pH1:"① 쓰는 트릭: 길게 누르기.", qt1pH2:"② 상자 안을 누른 채로 잠시 머물러라.", qt1pH3:"③ 첫 동작: 가운데 문구 위에 손가락을 올리고 떼지 않는다.",
      qt1zTag:"퀴즈 타워 1층 · 작아진 문패", qt1zRiddle:"문패가 너무 작다. 키워서 적힌 한 단어를 읽고, 그대로 입력해라.", qt1zBefore:"먼지 낀 문패에, 아주 작게 —", qt1zTiny:"등불", qt1zAfter:"읽었으면, 그 단어를 입력.", qt1zHint:"힌트: 회색 글상자를 두 손가락으로 키워 읽어라.", qt1zH1:"① 쓰는 트릭: 핀치 줌.", qt1zH2:"② 두 손가락을 벌려 작은 글자를 크게 본다.", qt1zH3:"③ 첫 동작: 회색 상자 위에서 두 손가락을 바깥으로 벌린다.",
      qt1tTag:"퀴즈 타워 1층 · 기운 수면", qt1tRiddle:"물그릇은 곧게 들면 어둡고, 기울이면 길을 비춘다.", qt1tHint:"힌트: 폰을 좌우로 기울여 수면을 맞춰라.", qt1tFbHint:"센서가 없으면 슬라이더를 끝까지 밀어라.", qt1tH1:"① 쓰는 트릭: 기울이기.", qt1tH2:"② 화면이 한쪽으로 충분히 기울면 문양이 떠오른다.", qt1tH3:"③ 첫 동작: 폰 오른쪽을 천천히 낮춰 본다.",
      qt1bTag:"퀴즈 타워 1층 · 먼지 낀 종", qt1bRiddle:"오래 울지 못한 종이 있다. 아주 작은 바람이면 충분하다.", qt1bHint:"힌트: 마이크에 숨을 보태거나, 폴백 버튼으로 게이지를 채워라.", qt1bH1:"① 쓰는 트릭: 불기.", qt1bH2:"② 마이크를 켜고 일정하게 후 불면 게이지가 오른다.", qt1bH3:"③ 첫 동작: 마이크 버튼을 누르고 짧게 불어 본다.",
      qt1rTag:"퀴즈 타워 1층 · 흩어진 발자국", qt1rRiddle:"계단에 작은 빛들이 흩어져 있다. 모두 이어야 한 층이 깨어난다.", qt1rHint:"힌트: 손가락으로 빛점을 모두 지나가라.", qt1rH1:"① 쓰는 트릭: 손가락 긋기.", qt1rH2:"② 캔버스의 점들을 하나도 빠뜨리지 않게 연결한다.", qt1rH3:"③ 첫 동작: 왼쪽 아래 첫 점에서 선을 시작한다.",
      qt1fTag:"퀴즈 타워 1층 · 작은 등", qt1fRiddle:"틈바람 속 등 하나. 가까이 감싸면 떨림이 줄어든다.", qt1fHint:"힌트: 두 손가락으로 등불 양옆을 감싸라.", qt1fH1:"① 쓰는 트릭: 감싸기.", qt1fH2:"② 두 손가락을 가까이 모은 채 보호 게이지를 올린다.", qt1fH3:"③ 첫 동작: 등불 양옆을 두 손가락으로 눌러 본다.",
      qt2rTag:"퀴즈 타워 2층 · 좁은 박자", qt2rRiddle:"이번 계단은 박자를 더 또렷이 듣는다. 왼쪽과 오른쪽, 엇갈려야 열린다.", qt2rHint:"힌트: 빛나는 노만 번갈아 눌러라.", qt2rH1:"① 쓰는 트릭: 좌우 노 젓기.", qt2rH2:"② 순서가 맞을 때만 전진한다.", qt2rH3:"③ 첫 동작: 먼저 빛나는 왼쪽 노를 누른다.",
      qt2fTag:"퀴즈 타워 2층 · 흔들리는 불", qt2fRiddle:"바람이 더 얇다. 감싸되, 오래 놓치지 말아야 한다.", qt2fHint:"힌트: 보호 게이지가 내려가지 않게 계속 감싸라.", qt2fH1:"① 쓰는 트릭: 감싸기.", qt2fH2:"② 두 손가락을 가까이 유지하면 보호가 쌓인다.", qt2fH3:"③ 첫 동작: 등불 옆을 감싸고 게이지가 오르는지 본다.",
      qt2pTag:"퀴즈 타워 2층 · 오래 머문 손", qt2pRiddle:"잠금쇠는 첫 층보다 더 늦게 안심한다. 서두르지 않는 손만 통과한다.", qt2pPress:"조용히 오래 머물기", qt2pHint:"힌트: 손을 올리고 충분히 기다려라.", qt2pH1:"① 쓰는 트릭: 길게 누르기.", qt2pH2:"② 중간에 떼면 다시 잠든다.", qt2pH3:"③ 첫 동작: 버튼 한가운데를 눌러 숨 한 번만 더 기다린다.",
      qt2tTag:"퀴즈 타워 2층 · 기운 물결", qt2tRiddle:"곧게 선 물은 모른 척한다. 더 낮게 기울인 손끝에만 길빛이 고인다.", qt2tHint:"힌트: 폰을 한쪽으로 충분히 기울여라.", qt2tFbHint:"센서가 없으면 슬라이더를 끝까지 밀어라.", qt2tH1:"① 쓰는 트릭: 기울이기.", qt2tH2:"② 첫 층보다 더 또렷하게 끝까지 기울여 본다.", qt2tH3:"③ 첫 동작: 폰 오른쪽을 천천히 낮추고 잠시 멈춘다.",
      qt2bTag:"퀴즈 타워 2층 · 깊은 숨의 종", qt2bRiddle:"먼지는 한 번에 흩어지지 않는다. 작고 고른 숨을 이어야 종 안쪽이 맑아진다.", qt2bHint:"힌트: 마이크에 일정하게 숨을 불어 게이지를 채워라.", qt2bH1:"① 쓰는 트릭: 불기.", qt2bH2:"② 짧게 끊기보다 고르게 이어 불면 더 안정적이다.", qt2bH3:"③ 첫 동작: 마이크 버튼을 누르고 낮은 숨을 길게 보낸다.",
      qt2gTag:"퀴즈 타워 2층 · 가는 별길", qt2gRiddle:"별빛은 더 촘촘히 놓였다. 손끝이 흔들려도, 하나도 빠뜨리지 않고 이어야 한다.", qt2gHint:"힌트: 캔버스의 모든 빛점을 손가락으로 지나가라.", qt2gH1:"① 쓰는 트릭: 손가락 긋기.", qt2gH2:"② 선이 끊겨도 괜찮지만 모든 점을 지나야 한다.", qt2gH3:"③ 첫 동작: 왼쪽 아래 첫 점에서 천천히 길을 긋는다.",
      qt2rpTag:"퀴즈 타워 2층 · 나란한 노", qt2rpRiddle:"혼자 젓는 박자로는 건너지 못한다. 두 노가 같은 숨에 물을 밀 때 강이 조용해진다.", qt2rpHint:"힌트: 양쪽 노를 거의 동시에 눌러 박자를 맞춰라.", qt2rpH1:"① 쓰는 트릭: 나란히 젓기.", qt2rpH2:"② 두 손가락으로 양쪽 노를 함께 누르면 게이지가 오른다.", qt2rpH3:"③ 첫 동작: 왼쪽과 오른쪽 노 위에 손가락을 하나씩 올린다.",
      qt2eTag:"퀴즈 타워 2층 · 손안의 불씨", qt2eRiddle:"작은 불씨는 급한 손을 무서워한다. 떼지 말고, 너무 서두르지 말고, 빈 등불까지 데려가라.", qt2eHint:"힌트: 불씨를 누른 채 천천히 빈 등불로 끌어라.", qt2eH1:"① 쓰는 트릭: 불씨 옮기기.", qt2eH2:"② 손을 떼면 꺼지고 처음으로 돌아간다.", qt2eH3:"③ 첫 동작: 왼쪽 불씨를 누른 채 오른쪽 등불 쪽으로 천천히 민다.",
      qt3tTag:"퀴즈 타워 3층 · 먼저 기울다", qt3tRiddle:"첫 고리는 수면을 비껴 보는 일. 기울어진 빛이 다음 바람을 부른다.", qt3tHint:"힌트: 먼저 기울여 표식을 깨워라.", qt3tFbHint:"센서가 없으면 슬라이더를 끝까지 밀어라.", qt3tH1:"① 쓰는 트릭: 기울이기.", qt3tH2:"② 이 문제는 다음 트릭으로 이어지는 첫 고리다.", qt3tH3:"③ 첫 동작: 폰을 한쪽으로 천천히 눕힌다.",
      qt3bTag:"퀴즈 타워 3층 · 이어 부는 바람", qt3bRiddle:"기울어진 길 위로 먼지가 오른다. 이번에는 숨으로 마지막 층을 밝힌다.", qt3bHint:"힌트: 마이크에 바람을 불어 게이지를 채워라.", qt3bH1:"① 쓰는 트릭: 불기.", qt3bH2:"② 앞 문제 뒤에 이어지는 두 번째 고리다.", qt3bH3:"③ 첫 동작: 마이크 버튼을 누르고 일정하게 숨을 분다.",
      qt3b2routeTag:"퀴즈 타워 3층 · 별실을 잇다", qt3b2routeRiddle:"먼 바람이 가라앉으면 별빛이 조용히 흩어진다. 손끝으로 물길을 먼저 엮어 두어라.", qt3b2routeHint:"힌트: 빛점을 모두 지나가며 길을 그려라.", qt3b2routeH1:"① 쓰는 트릭: 손가락 긋기.", qt3b2routeH2:"② 이 길은 다음 오래 머무는 손으로 이어진다.", qt3b2routeH3:"③ 첫 동작: 왼쪽 아래 빛에서 손끝을 출발시킨다.",
      qt3b2pressTag:"퀴즈 타워 3층 · 길 끝의 손", qt3b2pressRiddle:"이어 둔 물길 끝에 작은 문이 숨을 죽인다. 이제 그 앞에 손을 오래 놓아 안심시켜라.", qt3b2pressPress:"길 끝에 머물기", qt3b2pressHint:"힌트: 손을 떼지 말고 충분히 눌러라.", qt3b2pressH1:"① 쓰는 트릭: 길게 누르기.", qt3b2pressH2:"② 앞서 이은 길의 끝을 손바닥처럼 덮는다.", qt3b2pressH3:"③ 첫 동작: 가운데 문구를 누른 채 한 박자 더 기다린다.",
      qt3b3pressTag:"퀴즈 타워 3층 · 먼저 머물다", qt3b3pressRiddle:"이번 고리는 서두르지 않는 온기에서 시작한다. 닫힌 돌 위에 손을 얹고 작은 떨림이 잦아들게 해라.", qt3b3pressPress:"따뜻하게 머물기", qt3b3pressHint:"힌트: 오래 눌러 다음 빛을 깨워라.", qt3b3pressH1:"① 쓰는 트릭: 길게 누르기.", qt3b3pressH2:"② 충분히 머물면 기울일 물빛이 깨어난다.", qt3b3pressH3:"③ 첫 동작: 상자 한가운데를 누르고 떼지 않는다.",
      qt3b3tiltTag:"퀴즈 타워 3층 · 머문 뒤 기울다", qt3b3tiltRiddle:"손의 온기가 남은 돌 아래로 물이 흐른다. 이제 그 물을 한쪽으로 살며시 기울여 길빛을 받쳐라.", qt3b3tiltHint:"힌트: 폰을 한쪽으로 충분히 기울여라.", qt3b3tiltFbHint:"센서가 없으면 슬라이더를 끝까지 밀어라.", qt3b3tiltH1:"① 쓰는 트릭: 기울이기.", qt3b3tiltH2:"② 앞의 온기를 따라 물빛이 비스듬히 열린다.", qt3b3tiltH3:"③ 첫 동작: 폰 오른쪽을 천천히 낮추고 잠시 멈춘다.",
      qt3b4blowTag:"퀴즈 타워 3층 · 숨으로 띄우다", qt3b4blowRiddle:"가벼운 먼지가 별자리 위에 내려앉았다. 먼저 고른 숨으로 그 위를 부드럽게 비워라.", qt3b4blowHint:"힌트: 마이크에 일정하게 숨을 불어라.", qt3b4blowH1:"① 쓰는 트릭: 불기.", qt3b4blowH2:"② 숨이 길을 맑히면 곧 손끝으로 이을 차례다.", qt3b4blowH3:"③ 첫 동작: 마이크 버튼을 누르고 낮은 숨을 보낸다.",
      qt3b4routeTag:"퀴즈 타워 3층 · 숨 뒤의 별길", qt3b4routeRiddle:"비워진 자리마다 빛점이 떠오른다. 이제 숨이 닦아 둔 밤을 손끝으로 차례차례 건너라.", qt3b4routeHint:"힌트: 캔버스의 빛점을 모두 지나가라.", qt3b4routeH1:"① 쓰는 트릭: 손가락 긋기.", qt3b4routeH2:"② 앞의 숨이 만든 틈을 따라 선을 이어 간다.", qt3b4routeH3:"③ 첫 동작: 첫 빛점에서 천천히 선을 긋기 시작한다.",
      qt3b5rowTag:"퀴즈 타워 3층 · 물살을 맞추다", qt3b5rowRiddle:"낮은 배가 안개 속에서 기다린다. 왼쪽과 오른쪽을 번갈아 밀어, 기울일 물결을 먼저 모아라.", qt3b5rowHint:"힌트: 빛나는 노를 좌우 번갈아 눌러라.", qt3b5rowH1:"① 쓰는 트릭: 좌우 노 젓기.", qt3b5rowH2:"② 열네 번의 박자가 다음 기울임으로 이어진다.", qt3b5rowH3:"③ 첫 동작: 먼저 빛나는 왼쪽 노를 누른다.",
      qt3b5tiltTag:"퀴즈 타워 3층 · 젓고 기울이다", qt3b5tiltRiddle:"노가 남긴 잔물결이 한쪽으로 모인다. 이제 배의 기억처럼 화면을 기울여 숨은 길을 띄워라.", qt3b5tiltHint:"힌트: 폰을 한쪽으로 충분히 기울여라.", qt3b5tiltFbHint:"센서가 없으면 슬라이더를 끝까지 밀어라.", qt3b5tiltH1:"① 쓰는 트릭: 기울이기.", qt3b5tiltH2:"② 앞의 박자가 만든 물결을 한쪽으로 받아 낸다.", qt3b5tiltH3:"③ 첫 동작: 폰을 천천히 눕혀 물빛이 떠오를 때까지 기다린다.",
      qt3b6flameTag:"퀴즈 타워 3층 · 마지막 등", qt3b6flameRiddle:"가장 높은 틈바람이 작은 등을 흔든다. 먼저 두 손가락의 그늘로 불빛을 포근히 지켜라.", qt3b6flameHint:"힌트: 등불 양옆을 감싸 보호 게이지를 채워라.", qt3b6flameH1:"① 쓰는 트릭: 감싸기.", qt3b6flameH2:"② 천천히 차오른 불빛이 마지막 불씨로 이어진다.", qt3b6flameH3:"③ 첫 동작: 등불 양옆에 두 손가락을 가까이 둔다.",
      qt3b6emberTag:"퀴즈 타워 3층 · 불씨를 건네다", qt3b6emberRiddle:"지켜 낸 등에서 작은 불씨가 떨어진다. 손을 떼지 말고 천천히 빈 등불까지 데려가, 두 빛이 서로를 알아보게 해라.", qt3b6emberHint:"힌트: 불씨를 누른 채 천천히 빈 등불로 끌어라.", qt3b6emberH1:"① 쓰는 트릭: 불씨 옮기기.", qt3b6emberH2:"② 손을 떼면 꺼지니 끝까지 함께 간다.", qt3b6emberH3:"③ 첫 동작: 왼쪽 불씨를 누른 채 오른쪽 등불로 천천히 민다.",
      qtA4aTag:"퀴즈 타워 1-4 · 버티는 첫 별", qtA4aRiddle:"계단의 빛은 놓인 손을 믿지 않는다. 왼엄지로 닻을 잡고, 다른 손끝으로 흩어진 별을 이어라.", qtA4aHint:"힌트: 닻 패드를 누른 채 캔버스의 빛점을 모두 지나가라.", qtA4aH1:"① 쓰는 트릭: 버팀. 한 손은 닻, 한 손은 길.", qtA4aH2:"② 닻을 놓으면 그은 선이 빠르게 풀린다.", qtA4aH3:"③ 첫 동작: 왼쪽 닻 패드를 엄지로 누른 채 첫 별에서 선을 시작한다.",
      qtA4bTag:"퀴즈 타워 A4 · 사라지는 다리", qtA4bRiddle:"두 번째 다리는 오래 기다리지 않는다. 잡고 있는 동안에만 발판의 별들이 서로를 기억한다.", qtA4bHint:"힌트: 닻을 유지하면서 위아래로 갈라진 별길을 한 호흡에 이어라.", qtA4bH1:"① 닻 패드에서 시작한 손가락은 계속 누르고 있어야 한다.", qtA4bH2:"② 다른 손가락으로 오른쪽 캔버스의 별들을 모두 지난다.", qtA4bH3:"③ 멀티터치가 어려우면 접근성 잠금을 한 번 켠 뒤 그어라.",
      qtA4cTag:"퀴즈 타워 A4 · 남는 손", qtA4cRiddle:"마지막 별길은 조금 더 길다. 머무는 손이 있어야 떠나는 손끝의 궤적도 밤에 남는다.", qtA4cHint:"힌트: 닻을 떼지 말고 여섯 별을 모두 지나가라. 풀리면 다시 잡아라.", qtA4cH1:"① 왼손은 버티고, 오른손은 별을 잇는다.", qtA4cH2:"② 선이 붉게 흐려지면 닻이 풀린 것이다.", qtA4cH3:"③ 접근성 잠금은 폴백이다. 모바일에서는 두 손으로 버티면 가장 빠르다.",
      qtA4DoneTitle:"A4 점등", qtA4DoneBody:"잡고 있는 손 아래에서 길이 사라지지 않았다.<br>타워는 이제 네가 동시에 머물고 나아갈 수 있음을 안다.", qtA4DoneEnd:"— 버팀 완료 —",
      sc_tower_a5:"1-5 · 물때",
      tideBtn:"🎤 숨 켜기", tideFb:"수위 밀기", tidePrefix:"머묾 ", tideSet:"물때가 맞았다 ✦",
      qtA5Tag:"퀴즈 타워 1-5 · 물때", qtA5Riddle:"물이 너무 낮으면 닿지 않고, 너무 높으면 삼킨다. 숨을 띠 안에 머물게 해라.", qtA5Hint:"힌트: 약하지도 세지도 않게, 가운데 띠 안에서 숨을 유지한다. 세게 불면 진행이 크게 빠진다.", qtA5H1:"① 쓰는 트릭: 숨 조절.", qtA5H2:"② 게이지를 가운데 금빛 띠 안에 머물게 하면 진행된다.", qtA5H3:"③ 첫 동작: 마이크를 켜고 낮고 고른 숨으로 띠까지 올린다.", qtA5DoneTitle:"물때", qtA5DoneBody:"숨은 밀어붙이지 않고, 물은 넘치지 않았다.<br>타워는 이제 네가 힘보다 조절을 먼저 배웠음을 안다.", qtA5DoneEnd:"— 물때 완료 —",
      sc_tower_a2:"1-2 · 별가루",
      starShakeBtn:"흔들기 켜기", starShakeFb:"흔들기", starPrefix:"모임 ", starReady:"별자리 완성 — 이어라",
      qtA2Tag:"퀴즈 타워 1-2 · 별가루", qtA2Riddle:"흩어진 별을 흔들어 모으면, 이을 길이 드러난다.", qtA2Hint:"힌트: 기기를 가볍게 흔들어 별을 한자리에 모은 뒤, 손가락으로 잇는다.", qtA2H1:"① 쓰는 트릭: 흔들기.", qtA2H2:"② 별이 한곳에 모일 때까지 흔든다.", qtA2H3:"③ 모인 별을 한 획으로 잇는다.", qtA2DoneTitle:"별자리", qtA2DoneBody:"흩어져 있던 것들이 하나의 그림이 되었다.", qtA2DoneEnd:"길이 보인다.",
      sc_tower_a1:"1-1 · 문간",
      qtA1Tag:"퀴즈 타워 1-1 · 문간", qtA1Riddle:"낮엔 잠들고 밤에 깨어, 차고 또 기우는 얼굴 — 그것을 골라 지그시 눌러라.", qtA1Hint:"힌트: 수수께끼의 답에 해당하는 표식을 길게 눌러라. 틀린 표식은 열리지 않는다.", qtA1H1:"① 쓰는 트릭: 골라서 길게 누르기.", qtA1H2:"② 답은 밤·차오름·기욺과 관련된 표식.", qtA1H3:"③ 달 표식(☾)을 길게 누른다.", qtA1DoneTitle:"문간", qtA1DoneBody:"문지기는 이름이 아니라 답을 묻는다 — 너는 답했다.", qtA1DoneEnd:"문이 열린다.",
      sc_tower_a3:"1-3 · 톱니", dialPrefix:"맞춤 ",
      qtA3Tag:"퀴즈 타워 1-3 · 톱니", qtA3Riddle:"두 손가락으로 비틀어, 바늘을 표식에 맞춰 멈춰라.", qtA3Hint:"힌트: 두 손가락을 화면에 대고 시계/반시계로 비틀어 바늘을 목표 눈금에 맞춘 뒤 잠시 유지.", qtA3H1:"① 쓰는 트릭: 두 손가락 비틀기.", qtA3H2:"② 바늘이 밝아질 때(목표 근처)까지 돌린다.", qtA3H3:"③ 그 자리에서 잠깐 멈춰 유지한다.", qtA3DoneTitle:"맞물림", qtA3DoneBody:"톱니가 제자리를 찾아 맞물렸다.", qtA3DoneEnd:"다음이 열린다.",
      qtA6Tag:"퀴즈 타워 1-6 · 외줄",
      qtA6Riddle:"흔들리는 다리는 두 가지를 번갈아 요구한다. 폰을 기울여 공을 가운데 붙들고, 가운데에 머문 순간 다음 별을 하나씩 탭해라.",
      qtA6Hint:"힌트: 공이 가운데 있을 때만 빛난 다음 별을 순서대로 하나씩 탭해라.",
      qtA6H1:"① 쓰는 트릭: 외줄. 기울여 균형을 잡고, 중앙일 때 다음 별을 단발 탭한다.",
      qtA6H2:"② 순서가 아니거나 공이 중앙을 벗어난 탭은 길에 남지 않는다.",
      qtA6H3:"③ 센서가 없으면 좌우 균형 버튼으로 공을 가운데 되돌린 뒤 별을 하나씩 눌러라.",
      qtA6DoneTitle:"A6 점등", qtA6DoneBody:"기울어진 몸이 흔들림을 붙들고, 짧은 손끝이 별을 하나씩 건넜다.<br>타워는 이제 네가 떨림 속에서도 차례를 잃지 않음을 안다.", qtA6DoneEnd:"— 외줄 완료 —",
      sc_tower_a7:"1-7 · 마루",
      summitShakePrefix:"별 모음 ", summitPrefix:"버팀: ", summitDecayPrefix:"풀림: ", summitSet:"마루에 길이 남는다 ✦",
      qtA7Tag:"퀴즈 타워 1-7 · 마루",
      qtA7Riddle:"마지막 마루엔 흩어진 별이 떠 있다. 먼저 흔들어 별자리를 빚고, 그다음 닻을 잡은 채 한 획으로 이어라. 손을 놓으면 그은 길은 곧 풀려 사라진다.",
      qtA7Hint:"힌트: ①기기를 흔들어 별을 한자리에 모은다 ②닻 패드를 누른 채 ③모인 별을 한 획으로 모두 잇는다. 닻을 놓으면 선이 감쇠한다.",
      qtA7H1:"① 쓰는 트릭: 마루(종합). 흔들어 빚기 + 닻 잡고 잇기.",
      qtA7H2:"② 별이 다 모이기 전엔 캔버스에 그어지지 않는다. 모은 뒤에만 이을 수 있다.",
      qtA7H3:"③ 센서가 없으면 ‘흔들기’ 버튼으로 별을 모으고, 멀티터치가 어려우면 접근성 잠금을 켠 뒤 이어라.",
      qtA7DoneTitle:"A7 점등", qtA7DoneBody:"흩어진 것을 손으로 빚고, 잡은 채로 길을 남겼다.<br>타워는 이제 네가 빚기와 버팀을 한 호흡에 묶을 수 있음을 안다.", qtA7DoneEnd:"— 마루 완료 —",
      qt1DoneTitle:"1층 점등", qt1DoneBody:"낮은 층의 문들이 차례로 눈을 떴다.<br>타워는 네 손의 모양을 기억하기 시작한다.", qt1DoneEnd:"— 깨우기 완료 —",
      qt2DoneTitle:"2층 점등", qt2DoneBody:"박자와 보호가 조금 더 단단해졌다.<br>손끝이 길을 먼저 알아본다.", qt2DoneEnd:"— 손에 익히기 완료 —",
      qt3DoneTitle:"3층 점등", qt3DoneBody:"빛과 숨, 손과 물결이 차례로 이어졌다.<br>두 동작씩 묶인 문장들이 타워 안에 조용히 남았다.", qt3DoneEnd:"— 엮기 완료 —",
      // ── 측량가 시리즈 「그려둔 길」 (소설 중심) ──
      memTitle:"그려둔 길", memTag:"단편 소설",
      knotRoadLabel:"✍️ 그 한 줄을, 손으로", knotEraseLabel:"🌫 그 길을, 놓아주다",
      memShareTitle:"지도는 남는다", memShareBody:"그가 그려둔 길을, 네가 간직한다.",
      backToStory:"이야기로 돌아가기", memBackToStory:"이야기로 돌아가기",
      // 뱃사공 2단편 + 매듭 라벨
      learnTitle:"손을 배우는 밤", learnTag:"단편 · 첫 밤", crossTitle:"건너간 자리", crossTag:"단편 소설",
      knotTutorialLabel:"🕯 손으로 배우는 밤", knotSnowLabel:"🐕 곁에, 가만히", knotDawnLabel:"🚣 둘의 박자로", knotLanternLabel:"🔥 떼지 않고, 천천히",
      memStory:[
        "그는 길을 재는 사람이었다.",
        "마을과 마을, 강의 이쪽과 저쪽, 떠난 자리와 돌아올 자리 — 그 사이를 그는 걸음으로 재고, 줄로 재고, 끝내 종이 위에 옮겼다.",
        "사람들이 찾아와 물었다. 어떻게 가야 닿습니까. 그는 묻는 이의 얼굴을 오래 보고, 가닿고 싶은 곳을 듣고, 그 둘 사이에 길을 그렸다. 그가 그린 길은 한 번도 틀린 적이 없었다.",
        "그는 어떤 길이든 그릴 수 있었다. 물에 잠긴 길도, 아직 아무도 가지 않은 길도, 마음에서 마음으로 건너가는 길도.",
        "다만 한 가지. 제 마음에서 어느 한 사람에게로 가는 길만은, 그리지 못했다. 잴 수는 있었다. 매일 재고 있었다. 종이에 옮기는 일만, 한 번도 하지 못했다.",
        "✶",
        "그 사람은 자주 그의 곁에 앉아, 길이 그려지는 것을 보았다.",
        "먼 데를 그릴 때면 그 사람의 눈도 함께 멀어졌다. 그는 그 눈을 보지 않으려고 더 깊이 종이로 고개를 숙였다.",
        "그 사람은 그가 줄을 풀 때 끝을 잡아 주었고, 그가 밤늦도록 등을 밝히면 곁에서 심지를 돋우었다. 말은 적었다. 그 적은 말 사이가, 그가 잰 어떤 거리보다 가까웠다.",
        "어느 저녁, 그 사람이 물었다. 「당신은 모든 곳으로 가는 길을 아는데, 정작 당신이 가고 싶은 곳은 어디예요.」",
        "그는 줄을 감기만 했다. 가고 싶은 곳이 아니라 머물고 싶은 자리가 있다는 말을, 그 자리가 바로 곁이라는 말을, 끝내 옮기지 못했다.",
        "✶",
        "도시로 가는 길을 그려 달라고 그 사람이 말한 날, 그는 그 길을 가장 오래 그렸다. 가장 멀리, 가장 또렷이. 닳도록 재고 또 쟀다. 그렇게 길어진 것은 길이 아니라, 길을 그리는 시간이었다.",
        "떠나는 길목에서 그는 지도를 건넸다. 가지 마, 라고 하지 못했다. 기다릴게, 라고도 하지 못했다. 잴 수 없는 그 한 마디는 끝내 그의 안에 줄처럼 감긴 채 남았다.",
        "대신 그는 지도의 한 귀퉁이, 길에서 살짝 비켜난 빈자리에 작은 글씨로 한 줄을 적었다.",
        "⟦KNOT:road⟧",
        "그 사람은 지도를 접어 품에 넣고, 그려진 길을 따라 멀어졌다. 그는 그 자리에 남았다. 길을 그린 사람은 늘 길의 시작점에 남는 법이었다.",
        "✶",
        "해가 여러 번 떴다 졌다. 그는 여전히 사람들의 길을 그렸다. 혼인하러 가는 길, 장사하러 가는 길, 마지막 인사를 하러 가는 길. 닿고자 하는 모든 곳을 그는 그려 주었다.",
        "그 사람이 떠난 길은, 그 사람이 돌아오는 길이 되지 못했다. 길은 양쪽으로 났으나, 한쪽으로만 줄곧 비어 있었다.",
        "그의 곁에는 한 사람이 있었다. 이름을 부르지 않아도 곁에 있는 사람. 그가 길을 그릴 때 종이를 눌러 주고, 그가 먼 데를 보면 같이 먼 데를 보는 사람.",
        "그는 떠난 이에게 건넨 지도와 똑같은 한 장을 제 손으로 다시 그려, 깊은 데 두었다. 누구에게 가는 길인지는 말하지 않았다. 곁의 사람은 묻지 않았고, 다만 그 한 장이 어디 있는지를 가만히 외워 두었다.",
        "✶",
        "그는 늙었다. 잰 거리들이 몸 안에서 무거워졌다. 어느 날 그는, 잊기를 택했다. 잊는 것이 평온이었으므로.",
        "평온이 먼저 왔고, 다음엔 더듬음이 왔다. 끝내 그는, 가장 오래 그린 그 길이 누구에게로 가는 길이었는지조차 찾지 못했다. 줄을 풀면, 줄 끝엔 아무것도 매여 있지 않았다.",
        "그는 곁의 사람에게 말했다. 「편해진다는 건… 잊는다는 거지. 괜찮네, 그려도.」 그러고는 오래 만에 편안히, 빈 종이처럼 웃었다.",
        "⟦KNOT:erase⟧",
        "✶",
        "곁의 사람은 깊은 데 둔 그 한 장을 꺼냈다. 길에서 비켜난 빈자리에, 작은 글씨 한 줄이 그대로 있었다. 「가다가… 길 막히면, 여기로 와.」",
        "그가 잊은 길을, 이제 곁의 사람만이 알았다. 그 길이 누구에게서 누구에게로 났는지, 어디서 비어 버렸는지.",
        "곁의 사람은 지도를 접어 제 품에 넣었다. 떠난 이가 그랬던 것처럼. 그러나 이번엔 떠나기 위해서가 아니라, 남기 위해서였다.",
        "「잊혀도 — 지도는 남는다. 그가 잊은 길을, 이제 내가 간직한다.」",
        "언젠가 그 길이 다시 누군가를 부르는 날이 오면, 그가 끝내 걷지 못한 그 길을 대신 걸어 줄 사람이 여기 있었다. 길의 시작점에, 늘 그랬듯, 먼저 와서."
      ],
      // ── 뱃사공 단편 A 「손을 배우는 밤」(튜토리얼 이야기) ──
      learnStory:[
        "첫 밤, 그는 자기가 무엇인지 몰랐다.",
        "물 위에 배가 있었고, 배 안에 그가 있었고, 배 밖으로 누군가 손을 내밀고 있었다. 그 손을 어떻게 해야 하는지 그는 몰랐다. 등불을 어떻게 켜는지, 돛을 어떻게 올리는지, 노를 어떻게 젓는지 — 아무것도 몰랐다. 다만 오늘 밤, 그 모든 것을 처음으로 배워야 한다는 것만 알았다.",
        "가르쳐 줄 사람은 없었다. 잡아 줄 손도 없었다. 그는 제 손으로, 하나씩, 더듬어 익혀야 했다.",
        "⟦KNOT:tutorial⟧",
        "건너편에 닿았을 때, 손을 내밀었던 이는 마른 땅으로 올라섰다. 돌아보았는지 아닌지, 그는 보지 못했다. 다만 빈 배에 혼자 남아, 물 위에 떠서, 오래 흔들렸다.",
        "그때 그는 정했다. 늘 먼저 와 있겠다고. 떠난 뒤에도 남아 있겠다고. 누구의 것도 아닌 그 결심이, 그날 밤 그의 처음이자 전부였다."
      ],
      // ── 뱃사공 단편 B 「건너간 자리」(항해들) — 코다 본문 포함 ──
      crossStory:[
        "첫눈이 내리던 호수에서, 늙은 개 한 마리가 떨고 있었다.",
        "오래 누군가의 곁에 있던 짐승의 몸이었다. 떨림이 깊었다. 그는 다가가 곁에 앉았다. 말은 하지 않았다. 이제 그가 할 수 있는 일은 하나뿐이었다 — 곁에, 가만히, 오래.",
        "⟦KNOT:snow⟧",
        "건너편에 닿자 개는 마른 땅을 밟고 몇 걸음 걸어가더니, 한 번, 돌아보았다. 떠나는 눈이 아니었다. 곁에 있던 시간을 아는 눈, 오래 누군가의 곁에서 살아본 눈이었다. 그 눈이 그를 보았다.",
        "\"잘 가. 이쪽은 내가 지킬게.\"",
        "개는 다시 앞을 보고 걸어갔다. 그가 배로 돌아왔을 때, 배 바닥에 목줄 하나가 놓여 있었다. 풀려 떨어진 것이 아니라, 가지런히 — 그를 위해 둔 것이었다. 곁을 지킨다는 것이 무엇인지, 그 한 줌이 그의 안에 자리 잡았다.",
        "✶",
        "새벽 강에는 안개가 걷히고 있었다.",
        "아이 하나가 멀리 이사를 가는 길이었다. 보따리도 없이, 손이 가벼운 채였다. 아이가 노에 손을 얹었다. 혼자서는 건널 수 없는 물이었다. 둘이 박자를 맞춰야 했다.",
        "⟦KNOT:dawn⟧",
        "마른 땅에 닿자 아이는 폴짝 뛰어내렸다. 그러더니 뒤도 돌아보지 않고, 한 번도 돌아보지 않고, 풀밭을 가로질러 앞으로 달려갔다. 돌아볼 것이 없다는 건, 돌아볼 마음이 들지 않을 만큼 좋은 곳이 저 앞에 있다는 뜻이었다. 그는 그 등을, 작아질 때까지 바라보았다.",
        "배 안에는 종이배 하나가 남아 있었다. 아이가 접은 것이었다. 서툴게, 모서리가 맞지 않게. 가만 보니 노를 쥔 모양으로, 등을 살짝 굽힌 모양으로 — 그를 닮아 있었다. 두고 간 것이 아니라, 만들어서, 남긴 것이었다.",
        "✶",
        "등불 항구에서는, 한 사람의 기억이 꺼져가고 있었다.",
        "그는 작은 불씨를 손에 받았다. 그것을 항구 끝, 비어 있는 등불까지 옮겨야 했다. 손을 한 번이라도 들면 꺼질 불이었다. 떼지 않고, 아주 천천히.",
        "⟦KNOT:lantern⟧",
        "건너편에서 그 사람이 그를 보았다. 보았으나, 알아보지는 못했다. 이미 너무 많은 것을 잊은 뒤였다. 함께 건넌 일도, 불씨를 옮긴 일도, 그가 누구인지도. 그 눈에는 흐릿한 평온만 있었다. 잊은 자에게는 그편이 가볍다는 것을, 그는 알았다.",
        "\"잊혀도, 여기 한 칸은 비워둘게.\"",
        "그는 빈 등불에 불씨를 옮겨 붙였다. 등불은 이름이 없었다. 누구의 것이라 적혀 있지 않았다. 다만 켜졌다. 채우는 것과 똑같은 무게로, 비워두는 일의 한 줌이 그의 안에 들어왔다.",
        "✶",
        "마지막 밤의 배에는, 누군가를 만나러 가는 이가 탔다. 먼저 건너간 사람이, 건너편에서 아주 오래 기다린 사람이었다. 배에 탄 이는 조급하지 않았다. 다만 자꾸 건너편을 바라보았고, 그 눈에 두려움이 없었다. 물길은 더없이 잔잔하여, 노를 젓는 일이 마치 배웅이 아니라 마중 같았다.",
        "배가 닿자, 두 개의 작은 불빛이 마른 땅 위에서 서로에게로 다가갔다. 천천히, 사이의 거리를 좁히며. 그리고 하나가 되었다. 더 밝아지지는 않았다. 다만 더 따뜻해졌다.",
        "그는 노를 거두고, 그 광경이 온전히 끝날 때까지 바라보았다. 한 칸 비워두었던 자리는, 그가 지켜온 자리는, 그를 기다리던 자리였다. 그리고 조용히 고개를 끄덕였다.",
        "✶",
        "빈 배로 돌아오는 길, 멀리 건너편에서 작은 불빛 하나가 켜지는 것 같기도 했다. 아주 오래전부터 거기 있었던 것처럼.",
        "그는 노를 쥐었다. 그리고 기다렸다. 언젠가 누군가 그를 태우러 올 그 밤을 — 그날이면 그도 들을 것이었다. \"잘 가, 이쪽은 내가 지킬게\", 그 말을, 이번에는 그가.",
        "물은 잔잔했다. 등불은 꺼지지 않았다."
      ],
      // 작별 매듭(길 그리기)
      sc_road:"작별 · 그 한 줄",
      roadTag:"떠나는 길목",
      roadRiddle:"🌄 도시로 떠나는 그 사람. 길은 그릴 수 있었지만, 그 한마디는 끝내 못 했다.\n시작점(●)에서 도시(🏙)까지 — 길을 손끝으로 그어 이어라.",
      roadHint:"힌트: 시작점(●)에서 도시(🏙)까지 *손가락으로 길을 그어라*.",
      roadReveal:"「가다가… 길 막히면, 여기로 와.」",
      roadDoneTitle:"떠나는 길목",
      roadDoneBody:"길은 그어졌다. 그러나 가지 마, 도 기다릴게, 도 끝내 긋지 못한 채.<br>잴 수 없는 한 마디는, 그의 안에 줄처럼 감긴 채 남았다.",
      roadStay:"길을 그린 사람은, 늘 길의 시작점에 남는다.",
      roadCoda:"그가 적어 건넨 한 줄. 길에서 비켜난 빈자리에, 작은 글씨로.",
      roadDoneEnd:"— 그려둔 길 · 작별 —",
      // 망각 매듭(되짚어 지우기)
      sc_erase:"망각 · 놓아주다",
      eraseTag:"작업실 · 해질녘",
      eraseRiddle:"🕯 어느 날, 그는 잊기를 택했다. 잊는 것이 평온이므로.\n그어 둔 길을 — 끝(🏙)에서 시작점(●)으로, 거꾸로 천천히 되짚어 지워라.\n「편해진다는 건… 잊는다는 거지. 괜찮네, 그려도.」",
      eraseHint:"힌트: 그은 길을 *끝(🏙)에서부터 거꾸로* 천천히 되짚어 지워라.",
      eraseReveal:"그러고는 오래 만에, 빈 종이처럼 웃었다.",
      eraseDoneTitle:"작업실 · 해질녘",
      eraseDoneBody:"마지막 선이 사라진 자리에, 빈 종이 한 장이 남았다.",
      eraseSeq:["처음엔, 평온이 왔다.","떠난 길을 떠올려도 — 더는 안이 죄어들지 않았다.","다음엔, 더듬음이 왔다.","그 사람의 얼굴이 어느 쪽을 보고 있었는지.","떠난 길이 강의 이쪽이었는지, 저쪽이었는지.","끝내, 길을 잃었다.","가장 오래 그린 길이 하나 있었다는 것까지는 알았으나,","그 길이 누구에게로 가는 길이었는지는, 찾지 못했다.","줄을 풀면 — 줄 끝에, 아무것도 매여 있지 않았다."],
      eraseStay:"잊혀도 — 지도는 남는다. 그가 잊은 길을, 이제 내가 간직한다.",
      eraseCoda:"그가 놓아준 그 길을, 이제 너만이 안다.",
      eraseDoneEnd:"— 그려둔 길 · 망각 —",
      storyText:[
        "첫 밤, 그는 자기가 무엇인지 몰랐다.",
        "물 위에 배가 있었고, 배 안에 그가 있었고, 배 밖으로 누군가 손을 내밀고 있었다. 그는 그 손을 잡았다. 잡는 법을 몰라 오래 더듬었다. 등불에 불을 붙이는 일도 그랬다. 심지에 불을 가까이 대고, 옮겨붙을 때까지 손을 떨지 않고 가만히 오래 들고 있어야 한다는 걸, 그날 밤 그는 처음 알았다. 돛은 숨으로 올렸다. 가슴 가득 숨을 들이켜 천에 불어넣으면 천이 부풀고 배가 나아갔다. 그러다 바람이 사나워졌다. 노를 쥔 손이 떨렸다. 떨리는 손으로 그는 저었다. 멈추면 안 된다는 것만 알았다.",
        "건너편에 닿았을 때, 손을 내밀었던 이는 마른 땅으로 올라섰다. 돌아보았는지 아닌지, 그는 보지 못했다. 다만 빈 배에 혼자 남아, 물 위에 떠서, 오래 흔들렸다.",
        "그때 그는 정했다. 늘 먼저 와 있겠다고. 떠난 뒤에도 남아 있겠다고. 누구의 것도 아닌 그 결심이, 그날 밤 그의 처음이자 전부였다.",
        "✶",
        "첫눈이 내리던 호수에서, 늙은 개 한 마리가 떨고 있었다.",
        "오래 누군가 곁에 있던 짐승의 몸이었다. 그는 다가가 곁에 앉았다. 말은 하지 않았다. 다만 제 온기를 천천히 내주었다. 떨림이 잦아들 때까지. 개는 한참 만에 일어나 스스로 배에 올랐다.",
        "호수는 잔잔했다. 노를 저으면 동그란 무늬가 퍼졌다가 다시 평평해졌다. 눈은 소리 없이 내려, 개의 등에도 그의 어깨에도 쌓였다가 녹았다. 건너편에 닿자 개는 마른 땅을 밟고 몇 걸음 걸어가더니, 한 번, 돌아보았다. 오래 누군가의 곁에서 살아본 눈이었다. 떠나는 눈이 아니라, 곁에 있던 시간을 아는 눈이었다. 그 눈이 그를 보았다.",
        "\"잘 가. 이쪽은 내가 지킬게.\"",
        "개는 다시 앞을 보고 걸어갔다. 그가 배로 돌아왔을 때, 배 바닥에 목줄 하나가 놓여 있었다. 풀려 떨어진 것이 아니었다. 가지런히, 놓여 있었다. 그를 위해 둔 것이었다.",
        "그는 그것을 주워 가슴께에 갈무리했다. 빈 그릇 안으로, 한 줌이 들어왔다. 곁을 지킨다는 것이 무엇인지, 그날 그의 안에 한 줌만큼 자리 잡았다.",
        "✶",
        "새벽 강에는 안개가 걷히고 있었다.",
        "아이 하나가 멀리 이사를 가는 길이었다. 보따리도 없이, 손이 가벼운 채였다. 둘은 나란히 노를 저었다. 아이는 노 젓는 법을 금세 익혔다. 그를 곁눈으로 흘끔거리며, 손놀림을 따라 했다. 안개가 옅어질수록 건너편의 풀빛이 짙어졌다.",
        "마른 땅에 닿자 아이는 폴짝 뛰어내렸다. 그러더니 뒤도 돌아보지 않고, 한 번도 돌아보지 않고, 풀밭을 가로질러 앞으로 달려갔다. 돌아볼 것이 없다는 건, 돌아볼 마음이 들지 않을 만큼 좋은 곳이 저 앞에 있다는 뜻이었다. 그는 그 등을, 작아질 때까지 바라보았다.",
        "배 안에는 종이배 하나가 남아 있었다. 아이가 접은 것이었다. 서툴게, 모서리가 맞지 않게. 가만 보니 그것은 그를 닮아 있었다. 노를 쥔 모양으로, 등을 살짝 굽힌 모양으로. 흘끔거리던 곁눈은 그를 보고 있었던 것이다. 두고 간 것이 아니라, 만들어서, 남긴 것이었다.",
        "그는 종이배를 손바닥에 올렸다. 물에 젖으면 풀어질 만큼 약한 것이었으나, 젖지 않게 가슴께에 넣었다. 또 한 줌이 들어왔다. 누군가 나를 닮으려 했다는 것, 그 가벼운 것이 그의 안에 자리를 잡았다.",
        "✶",
        "등불 항구에서는, 한 사람의 기억이 꺼져가고 있었다.",
        "그는 작은 불씨를 손에 받았다. 그것을 항구 끝의 빈 등불까지 옮겨야 했다. 도중에 손을 들어 올리면 꺼질 것이었으므로, 그는 손을 들지 않았다. 천천히, 아주 천천히, 발끝으로 물을 밀며 나아갔다. 불씨가 바람에 눕고, 다시 서고, 또 누웠다. 그는 손을 가만히 오므려 그 위를 덮었다.",
        "빈 등불에 불씨를 옮겨 붙였다. 등불은 이름이 없었다. 누구의 것이라 적혀 있지 않았다. 다만 켜졌다.",
        "건너편에서 그 사람이 그를 보았다. 보았으나, 알아보지는 못했다. 이미 너무 많은 것을 잊은 뒤였다. 함께 건넌 일도, 불씨를 옮긴 일도, 그가 누구인지도. 그 눈에는 흐릿한 평온만 있었다. 잊은 자에게는, 그편이 가볍다는 것을 그는 알았다.",
        "\"잊혀도, 여기 한 칸은 비워둘게.\"",
        "그는 그렇게 말하고, 이름 없는 등불을 끄지 않았다. 항구에 등불 하나가 켜진 채 남았다. 누구의 것도 아닌, 그러나 비워둔 한 칸. 그의 안에 또 한 줌, 비워두는 일의 무게가 들어왔다. 채우는 것과 똑같은 무게로.",
        "✶",
        "마지막 밤의 배에는, 누군가를 만나러 가는 이가 탔다.",
        "먼저 건너간 사람이 있었다. 건너편에서, 아주 오래, 기다린 사람이었다. 배에 탄 이는 조급하지 않았다. 다만 자꾸 건너편을 바라보았다. 그 눈에 두려움이 없었다. 물길은 더없이 잔잔하여, 노를 젓는 일이 마치 배웅이 아니라 마중 같았다.",
        "건너편이 가까워지자, 그곳에 작은 불빛 하나가 서 있는 것이 보였다. 오래 기다린 불빛이었다. 배가 닿자, 탄 이가 천천히 내려섰다. 두 개의 작은 불빛이 마른 땅 위에서 서로에게로 다가갔다. 천천히, 사이의 거리를 좁히며. 그리고 하나가 되었다. 더 밝아지지는 않았다. 다만 더 따뜻해졌다.",
        "그는 노를 거두고, 그 광경이 온전히 끝날 때까지 바라보았다. 이번에 비워두었던 자리는, 그가 지켜온 자리는, 그를 기다리고 있던 자리였다. 누군가가 누군가를 기다리는 일을, 그는 처음부터 끝까지 보았다. 그리고 조용히 고개를 끄덕였다.",
        "✶",
        "빈 배로 돌아오는 길, 그는 제 안을 가만히 들여다보았다.",
        "목줄이 있었다. 종이배가 있었다. 이름 없는 등불이 한 칸을 밝히고 있었다. 마주 보다 하나가 된 불빛의 온기가 남아 있었다. 떠난 이들이 두고 간 것과, 그가 끝내 지킨 것들이, 한 줌씩 한 줌씩 쌓여, 빈 그릇이 어느새 묵직했다.",
        "처음에는 얼굴이 없었다. 이제 그는 어렴풋이, 제 손의 모양을 알았다. 곁에 앉는 법을, 손을 떨지 않고 불씨를 덮는 법을, 돌아보는 눈과 돌아보지 않는 등을 견디는 법을 알았다. 그는 그 모든 것으로 빚어진 사람이었다. 누군가를 건넬 때에만, 그는 비로소 형체를 얻었다.",
        "그는 늘 먼저 와 있었다. 떠난 뒤에도 남아 있었다.",
        "물 위로 밤이 깊어가고, 멀리 건너편에서, 작은 불빛 하나가 켜지는 것 같기도 했다. 아주 오래전부터 거기 있었던 것처럼. 누군가가, 이쪽을 향해, 가만히 지켜온 것처럼.",
        "그는 노를 쥐었다. 그리고 기다렸다. 언젠가의 밤을, 누군가 그를 태우러 올 그 밤을. 그날이면 그도 들을 것이었다. 잘 가, 이쪽은 내가 지킬게 — 그 말을, 이번에는 그가.",
        "물은 잔잔했다. 등불은 꺼지지 않았다."
      ],
      warmPrefix:"온기: ", warmSet:"떨림이 멎었다… 배에 오른다 🐕",
      endStay:"이쪽은 — 그대로 남아, 불을 켜 둔다.",
      shareTitle:"오늘 밤, 누군가가 무사히 건넜습니다.", shareBody:"건너편엔 등불 하나. 다음 사람의 첫 밤이 그 불로 밝습니다.",
      shareBtn:"🕯️ 등불을 다음 사람에게 →", shareText:"누군가를 건너편까지 바래다주세요 — 「건너편」.", backToHarbor:"길목으로 돌아가기",
      l1answer:"달빛", l2answer:"등대", l3answer:"수평선", l5answer:"북극성",
      answers:["달빛","등대","수평선","북극성"]
    },
    en: {
      title:"Yonderkeep",
      subtitle:"",
      reset:"↻ Restart",
      menu:"Menu",
      gatePrompt:"First time here?", gateYes:"Yes — begin from the start", gateNo:"No — take me to the crossroads",
      confirm:"Enter",
      placeholder:"passcode",
      ok:"Correct. Onward.",
      bad:"No. Try again.",
      gaugeInit:"tilt: —",
      gaugePrefix:"tilt: ",
      sensor:"📲 Tap to enable sensor (iOS)",
      l1tag:"SET SAIL · the dark harbor",
      l1riddle:"🌑 You came to see someone off — but the harbor is still dark.\nLight comes only to what waits, long and still.",
      l1press:"press — and hold",
      l1reveal:"moonlight",
      l1hint:"Hint: *press and hold* the screen.",
      l2tag:"SET SAIL · the soaked logbook",
      l2riddle:"📜 The truth is fine as a grain.\nPinch with two fingers to read it.",
      l2before:"Waves soak the paper all night. The ink bleeds; most of it means nothing.",
      l2tiny:"the passcode is lighthouse",
      l2after:"Yet one line, the smallest line, survived.",
      l2hint:"Hint: *pinch-zoom* the gray box.",
      l3tag:"SET SAIL · take the helm",
      l3riddle:"📱 Look straight on and you see nothing.\nTilt your phone sideways, until it lies level with the water.",
      l3secret:"horizon",
      l3hint:"Hint: tilt the phone left/right ~45° to reveal it.",
      l3fbhint:"No sensor? *Slide it all the way* to tilt and reveal.",
      l4tag:"SET SAIL · raise the sail",
      l4riddle:"🌬️ Now you truly leave. The sail hangs limp —\nadd your breath, and the boat moves.",
      l4hint:"Hint: *blow* into your phone's mic. (Fill the sail to set sail.)",
      l4windPrefix:"wind: ",
      l4windBtn:"🎤 Enable mic & prepare to sail",
      l4set:"The sail swells… setting sail 🌊",
      l4oar:"🚣 Row out (tap repeatedly)",
      l4oarPrefix:"rowing: ",
      l4oarSet:"You row out… setting sail 🌊",
      l5tag:"SET SAIL · the first channel",
      l5riddle:"✦ Nothing but dark sea. The guide is in the sky.\nConnect the scattered stars with your finger to draw the way.",
      l5hint:"Hint: drag to *connect all the stars*. (stuck? tap ‘redraw’)",
      l5clear:"↺ redraw",
      l5reveal:"polaris",
      l6tag:"FOG 1 · shelter the flame",
      l6riddle:"🌫️ The fog is thick. A small lantern wavers in the wind.\nCup it with two fingers and keep the flame alive.",
      l6hint:"Hint: bring two fingers around the lantern to *shelter* it. (one hand? press & hold ‘shield’ below)",
      l6shelterPrefix:"shelter: ",
      l6shelterBtn:"🤚 shield with one hand (hold)",
      l6set:"The flame holds steady… a warmth stays beside you 🕯️",
      l7tag:"STORM 1 · row",
      l7riddle:"🌊 The waves are fierce — you can't cross alone.\nTwo find the rhythm: pull the oars, left and right in turn.",
      l7hint:"Hint: tap the *glowing* oar, alternating left and right.",
      l7rowPrefix:"progress: ",
      l7set:"Through the storm… far off, stars appear ✦",
      l8tag:"FAREWELL · the recital",
      l8hint:"Hint: *press and hold* — keep holding, all the way to the end.",
      l8btn:"🤲 hold gently — to the end",
      l8lines:["Cup the last light, gently, in both hands.","Across the water — hand the lantern over.","Turn the empty boat's bow back toward home.","As you drift away, add one last breath to the sail."],
      l8end:"Go well. I'll keep this side.",
      doneTitle:"Voyage 🌅",
      doneBody:"It reached. The lantern blinks on the far shore,<br>and the empty boat turns home — alone.",
      doneEnd:"— end of the first voyage · fin —",
      sc_tutorial:"The First Night", hubTitle:"Crossroads",
      sc_snow:"Snow Lake — ferry the old dog",
      snow1tag:"SNOW LAKE · the shivering one", snow1riddle:"❄️ A lake under first snow. An old dog shivers, still.\nRest your hand beside it — long and quiet.", snow1press:"rest — your hand", snow1reveal:"warmth", snow1hint:"Hint: *press and hold* to share warmth.", snow_a1:"warmth",
      snow2tag:"SNOW LAKE · still ripples", snow2riddle:"🚣 The dog has boarded. Cross the still lake.\nPull the oars, left and right in turn.", snow2hint:"Hint: tap the *glowing* oar, alternating.",
      snowDoneTitle:"The Far Shore ❄️",
      snowDoneBody:"The old dog rested its chin on the bow, watching you the whole way across.<br>Stepping onto dry ground, it looked back — just once. With the eyes of someone you've lived beside for years.<br>\"You won't be cold now.\"",
      snowCoda:"As you turn the boat, a leash lies on the floor. Not slipped loose — left behind. For you.",
      snowDoneEnd:"— Snow Lake · fin —",
      sc_dawn:"Dawn River — ferry the child",
      dawnTag:"DAWN RIVER · side by side", dawnRiddle:"🌫️ The river at dawn, the fog lifting. The child who is leaving has boarded.\nMatch the child's rhythm — pull both oars *together*.", dawnHint:"Hint: press both oars *at once* (two fingers). One hand? tap ‘row together’ below.",
      rpPrefix:"progress: ", rpSet:"Across the river… the child looks ahead 🌅", rpSyncBtn:"🤲 row together (tap)",
      foldTag:"DAWN RIVER · a paper boat", foldRiddle:"🌫️ Nothing to give the leaving child. Just one worn sheet left by the river.\nWith your fingertips, slowly — *swipe* to fold it into a little boat.", foldHint:"Hint: *swipe* across the paper to fold, one crease at a time (three).",
      foldPrefix:"fold: ", foldSet:"A little boat, finished 🛶",
      dawnDoneTitle:"The Far Shore 🌅",
      dawnDoneBody:"The moment the child touched dry ground — they ran ahead. Without looking back, not once.<br>That was the good kind. Nothing to look back for means somewhere better is waiting.<br>\"Grow well there, too.\"",
      dawnCoda:"A paper boat drifted at your feet. Smaller and clumsier than the one you folded — made to look like you. Not left behind, but made, and left for you.",
      dawnDoneEnd:"— Dawn River · fin —",
      sc_lantern:"Lantern Harbor — ferry the fading one",
      emberTag:"LANTERN HARBOR · the ember", emberRiddle:"🪔 A harbor full of lanterns. Someone's memory is going out.\nCarry the ember — without lifting your hand, slowly — to the empty lantern.", emberHint:"Hint: *hold and drag slowly*. Lift your hand and it goes out.",
      emberPrefix:"carrying: ", emberSet:"The empty lantern catches light 🪔", emberOut:"The ember went out… again",
      lanternDoneTitle:"The Far Shore 🪔",
      lanternDoneBody:"Reaching the far shore, they looked at you — but did not know you. They had already forgotten too much.<br>And that was all right. It is lighter, for the one who forgets.<br>\"Even if you forget — I'll keep a place for you here.\"",
      lanternCoda:"Back in the harbor, one more lantern was lit. Its name tag empty — its flame the one you carried over. Forgotten, yet the place remains.",
      lanternDoneEnd:"— Lantern Harbor · fin —",
      sc_reunion:"Reunion — The Kept Place on the Far Shore",
      reunionTag:"REUNION · two lights", reunionRiddle:"✨ Someone who crossed before is still waiting.\nBring your light — without hurry, very slowly — to theirs.", reunionHint:"Hint: *hold and drag very slowly*. Rush or lift, and it stops.",
      reunionPrefix:"drawing near: ", reunionSet:"The two lights meet ✨", reunionOut:"It stopped… again, slowly",
      reunionDoneTitle:"The Far Shore ✨",
      reunionDoneBody:"The boat touches shore. The rocking stills.<br>They step off. Unhurried.",
      reunionSeq:["On the far side, a single light.","Small. An old light.","They stop.","…They know that light.","One step.","The light wavers. As if it looked back.","Another step.","Far off, someone rises.","From a place they'd sat a long time.","Their pace quickens.","No calling out. No need.","The gap between the two lights narrows.","Narrows,","and narrows,","and meets.","The space someone had kept open.","This time, that kept place had been waiting for them.","The two lights become one.","Not brighter. Only warmer.","The boatman watches.","Until the crossing is wholly done.","And quietly, nods."],
      reunionCoda:"He turns the empty bow toward home.",
      reunionDoneEnd:"Always there first; still there after. — fin —",
      libraryLabel:"Stories", storyTitle:"The Crossed Place", storyTag:"short story",
      seriesBoatman:"The Boatman", seriesMemory:"The Cartographer", seriesTower:"Quiz Tower", comingLabel:"Coming soon",
      towerProgress:"Current", hintCta:"Stuck? 💡 Hint",
      towerFloor1:"Floor 1", sc_tower_a4:"1-4 · Holdfast", sc_tower_a6:"1-6 · Tightrope",
      qtReveal:"✦ the way appears",
      holdPadLabel:"anchor pad",
      holdLockLabel:"accessibility lock",
      holdPrefix:"holdfast: ",
      holdDecayPrefix:"unmoored: ",
      holdSet:"the held path remains ✦",
      ropeSensorBtn:"enable tilt",
      ropeLeftBtn:"balance left",
      ropeRightBtn:"balance right",
      ropePrefix:"stars ",
      ropeReadyPrefix:"stars done · center: ",
      ropeSet:"the tightrope holds ✦",
      qt1pTag:"QUIZ TOWER F1 · long breath", qt1pRiddle:"A sleeping door remembers not a knock, but a hand that stays.", qt1pPress:"stay, softly", qt1pHint:"Hint: keep your hand down and wait.", qt1pH1:"① Trick: press and hold.", qt1pH2:"② Hold inside the box for a quiet moment.", qt1pH3:"③ First move: place a finger on the center text and do not lift it.",
      qt1zTag:"QUIZ TOWER F1 · the small nameplate", qt1zRiddle:"A nameplate is far too small. Enlarge it, read the single word, and type it.", qt1zBefore:"On a dusty nameplate, very small —", qt1zTiny:"lantern", qt1zAfter:"Once read, type that word.", qt1zHint:"Hint: pinch-zoom the gray text box to read it.", qt1zH1:"① Trick: pinch zoom.", qt1zH2:"② Spread two fingers to enlarge the tiny word.", qt1zH3:"③ First move: put two fingers on the gray box and spread them apart.",
      qt1tTag:"QUIZ TOWER F1 · tilted water", qt1tRiddle:"The bowl is dark when held straight; tilted, it reflects a way.", qt1tHint:"Hint: tilt the phone left or right to meet the waterline.", qt1tFbHint:"No sensor? Slide it all the way.", qt1tH1:"① Trick: tilt.", qt1tH2:"② A mark appears when the screen leans far enough.", qt1tH3:"③ First move: lower the right side of the phone slowly.",
      qt1bTag:"QUIZ TOWER F1 · dusty bell", qt1bRiddle:"A bell has not rung for a long time. A small breath is enough.", qt1bHint:"Hint: add breath to the mic, or fill the gauge with the fallback button.", qt1bH1:"① Trick: blow.", qt1bH2:"② Enable the mic and blow steadily to raise the gauge.", qt1bH3:"③ First move: tap the mic button and give a short breath.",
      qt1rTag:"QUIZ TOWER F1 · scattered steps", qt1rRiddle:"Little lights are scattered on the stairs. Join them all to wake the floor.", qt1rHint:"Hint: drag through every light point.", qt1rH1:"① Trick: finger tracing.", qt1rH2:"② Connect every point on the canvas without skipping one.", qt1rH3:"③ First move: begin the line at the lower-left point.",
      qt1fTag:"QUIZ TOWER F1 · small lamp", qt1fRiddle:"One lamp in a draft. Cup it close, and the trembling softens.", qt1fHint:"Hint: shelter both sides of the lamp with two fingers.", qt1fH1:"① Trick: sheltering.", qt1fH2:"② Keep two fingers close together to raise protection.", qt1fH3:"③ First move: press two fingers to either side of the lamp.",
      qt2rTag:"QUIZ TOWER F2 · narrow rhythm", qt2rRiddle:"This stair hears rhythm more clearly. Left and right must answer in turn.", qt2rHint:"Hint: tap only the glowing oar, alternating.", qt2rH1:"① Trick: left-right rowing.", qt2rH2:"② Only the correct order moves you forward.", qt2rH3:"③ First move: tap the glowing left oar first.",
      qt2fTag:"QUIZ TOWER F2 · wavering flame", qt2fRiddle:"The wind is thinner here. Shelter it, and do not lose it for long.", qt2fHint:"Hint: keep sheltering so the gauge does not fall.", qt2fH1:"① Trick: sheltering.", qt2fH2:"② Hold two fingers close to build protection.", qt2fH3:"③ First move: cup the lamp and watch for the gauge to rise.",
      qt2pTag:"QUIZ TOWER F2 · the patient hand", qt2pRiddle:"The latch trusts more slowly than the first floor. Only an unhurried hand passes.", qt2pPress:"stay a little longer", qt2pHint:"Hint: place your hand and wait long enough.", qt2pH1:"① Trick: press and hold.", qt2pH2:"② If you lift midway, it sleeps again.", qt2pH3:"③ First move: hold the center and wait one breath longer.",
      qt2tTag:"QUIZ TOWER F2 · leaning ripple", qt2tRiddle:"Upright water pretends not to know. Only a lower tilt gathers the path-light at your fingertips.", qt2tHint:"Hint: lean the phone far enough to one side.", qt2tFbHint:"No sensor? Slide it all the way.", qt2tH1:"① Trick: tilt.", qt2tH2:"② Lean more clearly than the first floor, all the way to the edge.", qt2tH3:"③ First move: lower the right side of the phone and pause.",
      qt2bTag:"QUIZ TOWER F2 · deep-breath bell", qt2bRiddle:"Dust does not scatter all at once. A small, even breath must continue until the bell clears inside.", qt2bHint:"Hint: blow steadily into the mic to fill the gauge.", qt2bH1:"① Trick: blow.", qt2bH2:"② A steady breath works better than short bursts.", qt2bH3:"③ First move: tap the mic button and send a low, long breath.",
      qt2gTag:"QUIZ TOWER F2 · narrow star-path", qt2gRiddle:"The lights are set closer together now. Even if your finger wavers, pass through every one.", qt2gHint:"Hint: drag through every light point on the canvas.", qt2gH1:"① Trick: finger tracing.", qt2gH2:"② The line may break, but every point must be visited.", qt2gH3:"③ First move: start at the lower-left light and draw slowly.",
      qt2rpTag:"QUIZ TOWER F2 · paired oars", qt2rpRiddle:"A solo rhythm cannot cross this water. When both oars push in one breath, the river quiets.", qt2rpHint:"Hint: press both oars almost at the same time.", qt2rpH1:"① Trick: paired rowing.", qt2rpH2:"② Two fingers on both oars together raise the gauge.", qt2rpH3:"③ First move: place one finger on each oar.",
      qt2eTag:"QUIZ TOWER F2 · ember in hand", qt2eRiddle:"A small ember fears a hurried hand. Do not lift, do not rush; carry it to the empty lantern.", qt2eHint:"Hint: hold the ember and drag it slowly to the empty lantern.", qt2eH1:"① Trick: ember carrying.", qt2eH2:"② Lift your hand and it goes out, returning to the start.", qt2eH3:"③ First move: hold the left ember and slowly push toward the right lantern.",
      qt3tTag:"QUIZ TOWER F3 · tilt first", qt3tRiddle:"The first link is seeing the water askew. Tilted light calls the next wind.", qt3tHint:"Hint: tilt first to wake the mark.", qt3tFbHint:"No sensor? Slide it all the way.", qt3tH1:"① Trick: tilt.", qt3tH2:"② This is the first link before the next trick.", qt3tH3:"③ First move: slowly lean the phone to one side.",
      qt3bTag:"QUIZ TOWER F3 · breath after light", qt3bRiddle:"Dust rises over the tilted path. Now breath lights the final floor.", qt3bHint:"Hint: blow into the mic to fill the gauge.", qt3bH1:"① Trick: blow.", qt3bH2:"② This is the second link after the previous puzzle.", qt3bH3:"③ First move: tap the mic button and blow steadily.",
      qt3b2routeTag:"QUIZ TOWER F3 · joining the star room", qt3b2routeRiddle:"When the far wind settles, starlight scatters softly. First weave a waterway with your fingertip.", qt3b2routeHint:"Hint: draw through every light point.", qt3b2routeH1:"① Trick: finger tracing.", qt3b2routeH2:"② This path leads into the next waiting hand.", qt3b2routeH3:"③ First move: begin from the lower-left light.",
      qt3b2pressTag:"QUIZ TOWER F3 · hand at the path's end", qt3b2pressRiddle:"At the end of the waterway, a small door holds its breath. Now rest your hand there long enough for it to trust you.", qt3b2pressPress:"stay at the path's end", qt3b2pressHint:"Hint: hold without lifting long enough.", qt3b2pressH1:"① Trick: press and hold.", qt3b2pressH2:"② Cover the end of the path you just joined.", qt3b2pressH3:"③ First move: hold the center text and wait one more beat.",
      qt3b3pressTag:"QUIZ TOWER F3 · stay first", qt3b3pressRiddle:"This link begins with unhurried warmth. Lay your hand on the closed stone and let the small trembling quiet down.", qt3b3pressPress:"stay warmly", qt3b3pressHint:"Hint: hold to wake the next light.", qt3b3pressH1:"① Trick: press and hold.", qt3b3pressH2:"② When you have stayed long enough, the waterlight for tilting wakes.", qt3b3pressH3:"③ First move: press the center of the box and do not lift.",
      qt3b3tiltTag:"QUIZ TOWER F3 · tilt after staying", qt3b3tiltRiddle:"Water moves beneath the stone warmed by your hand. Now lean that water gently to one side and catch the path-light.", qt3b3tiltHint:"Hint: lean the phone far enough to one side.", qt3b3tiltFbHint:"No sensor? Slide it all the way.", qt3b3tiltH1:"① Trick: tilt.", qt3b3tiltH2:"② The waterlight opens askew, following the warmth before it.", qt3b3tiltH3:"③ First move: lower the right side of the phone and pause.",
      qt3b4blowTag:"QUIZ TOWER F3 · lift with breath", qt3b4blowRiddle:"Fine dust has settled over a constellation. First clear it with one even, gentle breath.", qt3b4blowHint:"Hint: blow steadily into the mic.", qt3b4blowH1:"① Trick: blow.", qt3b4blowH2:"② The breath clears the space you will soon trace.", qt3b4blowH3:"③ First move: tap the mic button and send a low breath.",
      qt3b4routeTag:"QUIZ TOWER F3 · star-path after breath", qt3b4routeRiddle:"Light points rise in every cleared place. Now cross the night your breath made open, one fingertip at a time.", qt3b4routeHint:"Hint: pass through every light point on the canvas.", qt3b4routeH1:"① Trick: finger tracing.", qt3b4routeH2:"② Follow the space opened by the breath before it.", qt3b4routeH3:"③ First move: start a slow line from the first light point.",
      qt3b5rowTag:"QUIZ TOWER F3 · gather the current", qt3b5rowRiddle:"A low boat waits in the mist. Push left and right in turn, gathering the ripple you will tilt next.", qt3b5rowHint:"Hint: tap the glowing oars left and right in turn.", qt3b5rowH1:"① Trick: left-right rowing.", qt3b5rowH2:"② Fourteen beats lead into the next tilt.", qt3b5rowH3:"③ First move: tap the glowing left oar first.",
      qt3b5tiltTag:"QUIZ TOWER F3 · row, then tilt", qt3b5tiltRiddle:"The oars leave their ripples leaning together. Now tilt the screen like the boat remembers, and let the hidden way rise.", qt3b5tiltHint:"Hint: lean the phone far enough to one side.", qt3b5tiltFbHint:"No sensor? Slide it all the way.", qt3b5tiltH1:"① Trick: tilt.", qt3b5tiltH2:"② Receive the ripple made by the rhythm before it.", qt3b5tiltH3:"③ First move: slowly lean the phone until the waterlight appears.",
      qt3b6flameTag:"QUIZ TOWER F3 · the last lamp", qt3b6flameRiddle:"The highest draft shakes a small lamp. First shelter it in the soft shade of two fingers.", qt3b6flameHint:"Hint: shelter both sides of the lamp to fill the gauge.", qt3b6flameH1:"① Trick: sheltering.", qt3b6flameH2:"② The slowly steadied light leads into the final ember.", qt3b6flameH3:"③ First move: place two fingers close to either side of the lamp.",
      qt3b6emberTag:"QUIZ TOWER F3 · pass the ember", qt3b6emberRiddle:"A small ember falls from the lamp you protected. Do not lift; carry it slowly to the empty lantern, so the two lights may know each other.", qt3b6emberHint:"Hint: hold the ember and drag it slowly to the empty lantern.", qt3b6emberH1:"① Trick: ember carrying.", qt3b6emberH2:"② If you lift, it goes out, so stay with it to the end.", qt3b6emberH3:"③ First move: hold the left ember and slowly push toward the right lantern.",
      qtA4aTag:"QUIZ TOWER 1-4 · the first held star", qtA4aRiddle:"The stair lights do not trust a hand that only passes by. Hold the anchor with your left thumb, and join the scattered stars with another finger.", qtA4aHint:"Hint: keep the anchor pad pressed while you trace through every light point.", qtA4aH1:"① Trick: holdfast. One hand anchors; one hand draws.", qtA4aH2:"② Lift the anchor and the line rewinds quickly.", qtA4aH3:"③ First move: hold the left anchor pad with your thumb, then begin from the first star.",
      qtA4bTag:"QUIZ TOWER A4 · the vanishing bridge", qtA4bRiddle:"The second bridge does not wait long. Only while you keep hold do the stepping stars remember each other.", qtA4bHint:"Hint: keep the anchor held and draw the split star-path in one breath.", qtA4bH1:"① The finger that starts on the anchor pad must keep holding.", qtA4bH2:"② With another finger, pass through all stars on the right canvas.", qtA4bH3:"③ If multitouch is hard, tap the accessibility lock once, then draw.",
      qtA4cTag:"QUIZ TOWER A4 · the remaining hand", qtA4cRiddle:"The last star-path is a little longer. A staying hand lets the moving fingertip leave a mark in the night.", qtA4cHint:"Hint: do not release the anchor; pass through all six stars. If it unwinds, hold again.", qtA4cH1:"① The left hand stays; the right hand joins the stars.", qtA4cH2:"② If the line turns faint and red, the anchor has let go.", qtA4cH3:"③ The accessibility lock is the fallback. On mobile, two hands are the quickest way.",
      qtA4DoneTitle:"A4 Lit", qtA4DoneBody:"Under the hand that held fast, the path did not vanish.<br>The tower now knows you can stay and move at the same time.", qtA4DoneEnd:"— Holdfast complete —",
      sc_tower_a5:"1-5 · Tide",
      tideBtn:"🎤 enable breath", tideFb:"raise tide", tidePrefix:"held ", tideSet:"the tide holds ✦",
      qtA5Tag:"QUIZ TOWER 1-5 · tide", qtA5Riddle:"Too low, it cannot reach. Too high, it swallows. Keep your breath inside the band.", qtA5Hint:"Hint: hold the gauge inside the golden band. Blowing too hard drains progress quickly.", qtA5H1:"① Trick: breath control.", qtA5H2:"② Progress grows only while the gauge stays inside the golden band.", qtA5H3:"③ First move: enable the mic and send a low, even breath up to the band.", qtA5DoneTitle:"The Tide", qtA5DoneBody:"The breath did not shove, and the water did not spill.<br>The tower now knows you learned control before force.", qtA5DoneEnd:"— Tide complete —",
      sc_tower_a2:"1-2 · Stardust",
      starShakeBtn:"enable shake", starShakeFb:"shake", starPrefix:"gather ", starReady:"constellation set — connect it",
      qtA2Tag:"QUIZ TOWER 1-2 · stardust", qtA2Riddle:"Shake the scattered stars together, and a path to trace appears.", qtA2Hint:"Hint: gently shake the device to gather the stars into one place, then connect them with your finger.", qtA2H1:"① Trick: shake.", qtA2H2:"② Shake until the stars gather in one place.", qtA2H3:"③ Connect the gathered stars in one stroke.", qtA2DoneTitle:"A Constellation", qtA2DoneBody:"What was scattered became a single figure.", qtA2DoneEnd:"The way is clear.",
      sc_tower_a1:"1-1 · Antechamber",
      qtA1Tag:"QUIZ TOWER 1-1 · antechamber", qtA1Riddle:"Asleep by day, awake by night; a face that waxes and wanes — choose it and press, softly.", qtA1Hint:"Hint: long-press the mark that answers the riddle. The wrong marks will not open.", qtA1H1:"① Trick: choose, then press and hold.", qtA1H2:"② The answer relates to night, waxing and waning.", qtA1H3:"③ Long-press the moon mark (☾).", qtA1DoneTitle:"The Antechamber", qtA1DoneBody:"The gatekeeper asks not your name but an answer — and you answered.", qtA1DoneEnd:"The gate opens.",
      sc_tower_a3:"1-3 · Cogwork", dialPrefix:"align ",
      qtA3Tag:"QUIZ TOWER 1-3 · cogwork", qtA3Riddle:"Twist with two fingers to bring the needle onto the mark.", qtA3Hint:"Hint: place two fingers on the screen and twist clockwise/counter-clockwise to align the needle to the target, then hold briefly.", qtA3H1:"① Trick: two-finger twist.", qtA3H2:"② Turn until the needle glows (near the target).", qtA3H3:"③ Hold it there for a moment.", qtA3DoneTitle:"Engaged", qtA3DoneBody:"The cog found its place and meshed.", qtA3DoneEnd:"The next opens.",
      qtA6Tag:"QUIZ TOWER 1-6 · tightrope",
      qtA6Riddle:"A swaying bridge asks for two things in turn. Tilt the phone to keep the ball centered, then tap the next star one by one while it holds there.",
      qtA6Hint:"Hint: only when the ball is in the middle, tap the glowing next star in order.",
      qtA6H1:"① Trick: tightrope. Tilt for balance, then make a single tap on the next star while centered.",
      qtA6H2:"② A tap out of order, or while the ball has left center, does not stay on the path.",
      qtA6H3:"③ No sensor? Use the left/right balance buttons to bring the ball back, then tap each star.",
      qtA6DoneTitle:"A6 Lit", qtA6DoneBody:"Your leaning body held the shake, and your brief fingertip crossed the stars one by one.<br>The tower now knows you can keep sequence inside a tremor.", qtA6DoneEnd:"— Tightrope complete —",
      sc_tower_a7:"1-7 · Summit",
      summitShakePrefix:"gather ", summitPrefix:"holdfast: ", summitDecayPrefix:"unmoored: ", summitSet:"the summit path remains ✦",
      qtA7Tag:"QUIZ TOWER 1-7 · summit",
      qtA7Riddle:"On the final summit, scattered stars drift. First shake them into a constellation, then trace it in one stroke while you hold the anchor. Let go, and the line you drew soon unravels.",
      qtA7Hint:"Hint: ① shake the device to gather the stars ② keep the anchor pad pressed ③ join all the gathered stars in one stroke. Release the anchor and the line decays.",
      qtA7H1:"① Trick: summit (synthesis). Shake to shape + hold the anchor to join.",
      qtA7H2:"② Until the stars gather, the canvas will not draw. Only after they converge can you trace.",
      qtA7H3:"③ No sensor? Tap the ‘shake’ button to gather. If multitouch is hard, turn on the accessibility lock, then trace.",
      qtA7DoneTitle:"A7 Lit", qtA7DoneBody:"You shaped the scattered with your hand, and kept the path while holding fast.<br>The tower now knows you can bind shaping and holdfast in a single breath.", qtA7DoneEnd:"— Summit complete —",
      qt1DoneTitle:"Floor 1 Lit", qt1DoneBody:"The lower doors wake one by one.<br>The tower begins to remember the shape of your hands.", qt1DoneEnd:"— Waking complete —",
      qt2DoneTitle:"Floor 2 Lit", qt2DoneBody:"Rhythm and shelter have grown steadier.<br>Your fingertips know the way a little sooner.", qt2DoneEnd:"— Into the Hands complete —",
      qt3DoneTitle:"Floor 3 Lit", qt3DoneBody:"Light and breath, hand and ripple followed one another.<br>Paired motions stayed in the tower as quiet sentences.", qt3DoneEnd:"— Linking complete —",
      // ── Cartographer series: "The Drawn Road" (novel-first) ──
      memTitle:"The Drawn Road", memTag:"short story",
      knotRoadLabel:"✍️ That one line, by hand", knotEraseLabel:"🌫 Let the road go",
      memShareTitle:"The map remains", memShareBody:"The road he drew is yours to keep.",
      backToStory:"Back to the story", memBackToStory:"Back to the story",
      // Boatman two short stories + knot labels
      learnTitle:"The Night of Learning Hands", learnTag:"short · first night", crossTitle:"The Crossed Place", crossTag:"short story",
      knotTutorialLabel:"🕯 The night, learned by hand", knotSnowLabel:"🐕 Beside, and still", knotDawnLabel:"🚣 For the two of us, in time", knotLanternLabel:"🔥 Without lifting, slowly",
      memStory:[
        "He was a man who measured roads.",
        "From village to village, from this bank to the far bank, from the place left behind to the place one hoped to return — he measured with his steps, then with his cord, and finally laid it all down on paper.",
        "People came to him and asked, How do I get there? He would study the face of the one asking, listen for the place they longed to reach, and draw the road between. The roads he drew were never wrong.",
        "He could draw any road: roads sunk underwater, roads no one had walked yet, roads that crossed from one heart to another.",
        "Only one road would not come. The road from his own heart to a certain person — that one he could not draw. He could measure it. He measured it every day. But he never once put it down on paper.",
        "✶",
        "That person often sat beside him, watching the roads take shape.",
        "When he drew faraway places, that person's eyes traveled far with them. He bent lower over the paper so he would not have to meet those eyes.",
        "That person held the end of his cord when he unspooled it, and trimmed the wick beside him when the lamp burned late. They said little. The space between those few words was closer than any distance he had ever measured.",
        "One evening, that person asked, \"You know the road to everywhere — so where is it you want to go?\"",
        "He only wound the cord back in. It was not a place he wanted to reach, but a place he wanted to stay. That the place was right here, beside them, he never wrote down.",
        "✶",
        "The day that person asked him to draw the road to the city, he spent longer on it than on any road before. The farthest, the clearest. He measured it until the measuring itself wore thin. It was not the road that grew long, but the time he took to draw it.",
        "At the parting fork he handed over the map. Don't go, he could not say. I'll wait, he could not say either. That unmeasurable line stayed coiled inside him like cord.",
        "Instead, in one corner of the map — in an empty space just off the road — he wrote a single line in small letters.",
        "⟦KNOT:road⟧",
        "That person folded the map into their coat and went away along the road he had drawn. He stayed where he was. The one who draws the road always remains at the starting point.",
        "✶",
        "The sun rose and set many times. He still drew people's roads. The road to a wedding, the road to trade, the road to a last farewell. Every place they longed to reach, he drew for them.",
        "The road by which that person left never became the road by which they returned. The road ran both ways, but one direction stayed empty all the while.",
        "Beside him was another person: someone who stayed near without needing to be called by name, who pressed the paper flat while he drew, who looked into the distance when he did.",
        "With his own hand, he drew another map exactly like the one he had given away, and hid it deep. He did not say whom the road was for. The one beside him did not ask — only quietly memorized where that single sheet was kept.",
        "✶",
        "He grew old. The distances he had measured grew heavy inside him. One day, he chose to forget. For forgetting was peace.",
        "Peace came first, and then the groping. In the end, he could no longer find even whom that longest-drawn road had been for. Unspool the cord, and nothing was tied to its end.",
        "He said to the one beside him, \"To be at peace… is to forget. It's all right. Draw it.\" And then, for the first time in a long while, he smiled — blank as fresh paper.",
        "⟦KNOT:erase⟧",
        "✶",
        "The one beside him took out the single sheet he had hidden away deep. In the empty space off the road, a line in small letters was still there. \"If the road ahead is blocked… come back here.\"",
        "The road he had forgotten — now only the one beside him knew it. Whom it ran from, whom it ran to, and where it had gone empty.",
        "The one beside him folded the map into their own coat, as that person once had. But this time, not to leave — to remain.",
        "\"Forgotten — yet the map remains. The road he forgot, now I keep.\"",
        "Someday, when that road calls someone again, there will be someone here to walk, in his place, the road he never could. At the starting point, as ever, already waiting."
      ],
      // ── Boatman story A "The Night of Learning Hands" (tutorial) ──
      learnStory:[
        "On the first night, he did not know what he was.",
        "There was a boat on the water, and he was in the boat, and beyond the boat someone was holding out a hand. He did not know what to do with that hand. How to light the lamp, how to raise the sail, how to row — he knew none of it. He knew only that tonight, for the first time, he had to learn it all.",
        "There was no one to teach him. No hand to hold his. With his own hands, he had to grope his way and learn, one thing at a time.",
        "⟦KNOT:tutorial⟧",
        "When he reached the far side, the one who had held out a hand stepped onto dry land. Whether they looked back, he did not see. He only stayed in the empty boat, afloat, swaying a long while.",
        "That night he decided: to come first, always. To remain even after they had gone. That resolve, belonging to no one, was his first possession, and that night it was everything."
      ],
      // ── Boatman story B "The Crossed Place" (voyages) — codas kept in the body ──
      crossStory:[
        "On a lake where the first snow was falling, an old dog stood trembling.",
        "Its body was that of a creature that had long been at someone's side. The trembling was deep. He went near and sat beside it. He said nothing. There was only one thing he could do now — to be beside it, still, for a long while.",
        "⟦KNOT:snow⟧",
        "Reaching the far side, the dog stepped onto dry land, walked a few paces, and looked back, once. Not the look of one who was leaving. The look of one who knows the time spent beside another: eyes that had lived long at someone's side. Those eyes saw him.",
        "\"Go well. This side, I'll keep.\"",
        "The dog faced forward and walked on. When he returned to the boat, a collar lay on its floor. Not slipped loose, but set down neatly — left for him. What it means to keep watch beside someone — that one handful settled inside him.",
        "✶",
        "On the dawn river the mist was lifting.",
        "A child was about to move far away. No bundle, hands light. The child laid a hand on the oar. It was water no one could cross alone. The two had to keep time together.",
        "⟦KNOT:dawn⟧",
        "On reaching dry land, the child leapt off, and then, without looking back, not once looking back, ran ahead across the grass. To have nothing to look back on means there is something good enough ahead that the wish to look back never comes. He watched that small back until it grew smaller.",
        "In the boat a paper boat remained. The child had folded it — clumsily, corners unmatched. Looking closer, he saw the shape of a hand at the oar, of a back slightly bent — it resembled him. Not left behind, but made, and left.",
        "✶",
        "At the lantern harbor, someone's memory was going out.",
        "He received a small ember in his hand. He had to carry it to an empty lamp at the harbor's end. If he lifted his hand even once, it would die. Without lifting it, ever so slowly.",
        "⟦KNOT:lantern⟧",
        "From the far side that person saw him. Saw, but did not know him. Too much had already been forgotten. The crossing together, the carrying of the ember, who he was. In those eyes was only a dim peace. To one who has forgotten, he knew, that is the lighter way.",
        "\"Even forgotten — I'll keep one space here, empty.\"",
        "He set the ember to the empty lamp. The lamp had no name. It was not written whose it was. Yet it was lit. With the same weight as fullness, that one handful — the keeping of a space empty — entered him.",
        "✶",
        "On the boat of the last night rode someone going to meet another. There was one who had crossed first, who had waited on the far side a very long time. The rider was not impatient — only kept looking to the far side, and in those eyes was no fear. The water was so still that rowing felt less like a sending-off than a going-to-meet.",
        "When the boat touched, two small lights drew toward each other over the dry land. Slowly, closing the distance between them. And they became one. They did not grow brighter. Only warmer.",
        "He drew in the oar and watched until the sight was wholly done. The one space he had kept empty, the place he had guarded, was the place that had been waiting for him. And he quietly nodded.",
        "✶",
        "On the way back in the empty boat, far off on the other side, a small light seemed almost to come on. As if it had been there since long, long ago.",
        "He took up the oar. And he waited. For the night, someday, when someone would come to carry him — that night, he too would hear it. \"Go well, this side I'll keep,\" the words, this time, from him.",
        "The water was still. The lamp did not go out."
      ],
      // Farewell knot (drawing the road)
      sc_road:"Farewell · that one line",
      roadTag:"THE PARTING FORK",
      roadRiddle:"🌄 That person is leaving for the city. He could draw the road — but not the words he meant to say.\nFrom the start (●) to the city (🏙) — draw the road with your fingertip and join them.",
      roadHint:"Hint: *draw the road with your finger* — from the start (●) to the city (🏙).",
      roadReveal:"\"If the road ahead is blocked… come back here.\"",
      roadDoneTitle:"The Parting Fork",
      roadDoneBody:"The road was drawn. But neither \"Don't go\" nor \"I'll wait\" could be.<br>The unmeasurable line stayed coiled inside him like cord.",
      roadStay:"The one who draws the road always remains at the starting point.",
      roadCoda:"The one line he wrote and handed over. In an empty spot off the road, in small letters.",
      roadDoneEnd:"— The Drawn Road · Farewell —",
      // Forgetting knot (retrace and erase)
      sc_erase:"Forgetting · letting go",
      eraseTag:"The Workshop · dusk",
      eraseRiddle:"🕯 One day, he chose to forget. For forgetting was peace.\nThe road you drew — from the end (🏙) back to the start (●), slowly retrace and erase it.\n\"To be at peace… is to forget. It's all right. Draw it.\"",
      eraseHint:"Hint: *retrace the drawn road backward* — slowly, from the end (🏙).",
      eraseReveal:"And then, for the first time in a long while, he smiled — blank as fresh paper.",
      eraseDoneTitle:"The Workshop · dusk",
      eraseDoneBody:"Where the last line vanished, a single blank sheet remained.",
      eraseSeq:["First came peace.","Even recalling the road now gone — nothing tightened inside him anymore.","Then came the groping.","Which way that person's face had been turned.","Whether the road that left was this bank of the river, or the far one.","At last, he lost the road.","He knew this much — that there had been one road he drew longest of all,","but whom that road was for, he could not find.","Unspool the cord — and at its end, nothing was tied."],
      eraseStay:"Forgotten — yet the map remains. The road he forgot, now I keep.",
      eraseCoda:"The road he let go of — now only you know it.",
      eraseDoneEnd:"— The Drawn Road · Forgetting —",
      storyText:[
        "On the first night, he did not know what he was.",
        "There was a boat on the water, and he was in it, and beyond the boat someone was holding out a hand. He took it. He did not know how to take a hand, and fumbled a long while. Lighting the lantern was the same. To bring the flame close to the wick and hold it there, hands unshaking, long and still until it caught — that, he learned for the first time that night. The sail he raised with breath. Draw a chestful of air, breathe it into the cloth, and the cloth swells and the boat moves. Then the wind turned fierce. The hands on the oars trembled. With trembling hands he rowed. He knew only that he must not stop.",
        "When they reached the far side, the one who had held out a hand stepped onto dry ground. Whether they looked back, he did not see. He only remained, alone in the empty boat, afloat on the water, rocking a long time.",
        "That was when he decided: to be there first, always. To remain, even after they had gone. That resolve was the first thing that was truly his, and for that night, it was everything.",
        "✶",
        "On a lake under the first snow, an old dog was shivering.",
        "It had the body of a creature that had long lived at someone's side. He went to it and sat beside it. He did not speak. He only gave his warmth, slowly. Until the trembling eased. After a long while the dog rose and boarded the boat on its own.",
        "The lake was still. When he rowed, round ripples spread and went flat again. The snow fell without a sound, gathering on the dog's back and on his shoulders and melting. When they reached the far side the dog stepped onto dry ground, walked a few paces, and — once — looked back. They were the eyes of one who had spent a lifetime beside someone. Not the eyes of leaving, but eyes that knew the time spent beside someone. Those eyes looked at him.",
        "\"Go well. I'll keep this side.\"",
        "The dog faced forward again and walked on. When he returned to the boat, a leash lay on its floor. It had not slipped loose. It lay, neatly. It had been left for him.",
        "He picked it up and tucked it close to his chest. Into the empty vessel, a handful settled within him. What it means to keep someone's side took root in him that day, a handful's worth.",
        "✶",
        "On the dawn river the fog was lifting.",
        "A child was about to move far away. No bundle, hands light. The two of them rowed side by side. The child learned to row at once, stealing glances at him, copying the motion of his hands. As the fog thinned, the green of the far bank deepened.",
        "On reaching dry ground, the child hopped off. And then, without looking back, not once, ran ahead across the grass. To have nothing to look back for meant somewhere good enough to leave looking-back behind lay up ahead. He watched that small back until it grew smaller still.",
        "In the boat a paper boat remained. The child had folded it. Clumsily, the corners not meeting. Looking closely, it resembled him. The shape of hands on the oars, the back slightly bent. Those stolen glances had been meant for him all along. Not left behind, but made, and left.",
        "He set the paper boat on his palm. It was frail enough to come undone if wet, but he tucked it close to his chest, where it would not. Another handful settled within him. That someone had wanted to resemble him — that light thing took its place in him.",
        "✶",
        "At the lantern harbor, someone's memory was going out.",
        "He received a small ember in his hand. He had to carry it to an empty lantern at the harbor's end. If he lifted his hand on the way, it would go out, so he did not lift it. Slowly, very slowly, pushing the water with the tips of his feet, he went. The ember bent low in the wind, then flared again, then bent low once more. He gently cupped his hand over it.",
        "He moved the ember to the empty lantern. The lantern had no name. It was not written whose it was. It only lit.",
        "From the far side the person looked at him. Looked, but did not know him. They had already forgotten too much. The crossing together, the carrying of the ember, who he was. In those eyes was only a dim peace. For the one who forgets, he knew, that way is lighter.",
        "\"Even if you're forgotten — I'll keep one space here.\"",
        "So he said, and did not put out the nameless lantern. One lantern stayed lit at the harbor. No one's, and yet a space kept open. Another handful settled within him — the weight of keeping a place open. The very same weight as fullness.",
        "✶",
        "On the boat of the last night rode someone going to meet another.",
        "There was a person who had crossed before. On the far side, a very long time, they had waited. The one aboard was not impatient. They only kept looking to the far side. There was no fear in their eyes. The water was so utterly still that the rowing felt not like a sending-off but a going-to-meet.",
        "As the far side drew near, a single small light was seen standing there. A light that had waited long. When the boat touched, the one aboard stepped slowly down. Two small lights, on the dry ground, drew toward each other. Slowly, closing the distance between them. And became one. Not brighter. Only warmer.",
        "He drew in his oars and watched until it was wholly done. The place kept open this time, the place he had guarded, was a place that had been waiting for them. He saw, from beginning to end, one waiting for another. And quietly, he nodded.",
        "✶",
        "On the way back in the empty boat, he looked quietly into himself.",
        "There was a leash. There was a paper boat. A nameless lantern lit one space. The warmth of two lights that had faced each other and become one remained. What those who left had left behind, and what he had kept to the end, gathered handful by handful, until the empty vessel was, somewhere along the way, heavy.",
        "At first he had no face. Now he knew, faintly, the shape of his own hands. He knew how to sit beside, how to cup an ember with unshaking hands, how to bear the eyes that look back and the back that does not. He was a person shaped by all of it. Only when he carried someone did he, at last, take form.",
        "He was always there first. He remained, even after they had gone.",
        "The night deepened over the water, and far off on the other side, a single small light seemed, perhaps, to come on. As if it had been there a very long time. As if someone, facing this side, had quietly kept watch.",
        "He took up the oars. And waited. For some night — the night when someone would come to carry him. On that night he too would hear it — Go well, I'll keep this side — those words, this time, from him.",
        "The water was still. The lantern did not go out."
      ],
      warmPrefix:"warmth: ", warmSet:"The shivering stops… it climbs aboard 🐕",
      endStay:"This side — someone stays, keeps the light.",
      shareTitle:"Tonight, someone made it across.", shareBody:"On the far side, one lantern. It will light the next person's first night.",
      shareBtn:"🕯️ Pass the lantern onward →", shareText:"See someone all the way to the far side — Yonderkeep.", backToHarbor:"Back to the crossroads",
      l1answer:"moonlight", l2answer:"lighthouse", l3answer:"horizon", l5answer:"polaris",
      answers:["moonlight","lighthouse","horizon","polaris"]
    }
  };
